CREATE SEQUENCE APFS.SEQ_USER START 1;
CREATE SEQUENCE APFS.SEQ_MAIL_HST START 1;
CREATE SEQUENCE APFS.SEQ_APLY_FILE START 1;
CREATE SEQUENCE APFS.SEQ_FILE START 1;
CREATE SEQUENCE APFS.SEQ_BBS START 1;

CREATE TABLE APFS.TMP_USER (
	USER_NO VARCHAR(20) NOT NULL,
	USER_ID VARCHAR(100),
	USER_NM VARCHAR(40),
	USER_CD VARCHAR(10),
	PSWD  VARCHAR(100),
	EMAIL VARCHAR(100),
	MOBILE VARCHAR(20),
	JOIN_YMD VARCHAR(8),
	WHDWL_YMD VARCHAR(8),
	PSWD_LOCK_YMD VARCHAR(8),
	PSWD_ERR_CNT SMALLINT,
	PSWD_CHG_YMD VARCHAR(8),
	PSWD_NEXT_YMD VARCHAR(8),
	LST_LGN_DT DATE,
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (USER_NO)
);
COMMENT ON TABLE  APFS.TMP_USER IS '사용자정보';
COMMENT ON COLUMN APFS.TMP_USER.USER_NO IS '사용자번호';
COMMENT ON COLUMN APFS.TMP_USER.USER_ID IS '사용자ID';
COMMENT ON COLUMN APFS.TMP_USER.USER_NM IS '사용자명';
COMMENT ON COLUMN APFS.TMP_USER.USER_CD IS '사용자가입유형';
COMMENT ON COLUMN APFS.TMP_USER.PSWD IS '비밀번호';
COMMENT ON COLUMN APFS.TMP_USER.EMAIL IS '이메일';
COMMENT ON COLUMN APFS.TMP_USER.MOBILE IS '휴대전화번호';
COMMENT ON COLUMN APFS.TMP_USER.JOIN_YMD IS '가입일자';
COMMENT ON COLUMN APFS.TMP_USER.WHDWL_YMD IS '탈퇴일자';
COMMENT ON COLUMN APFS.TMP_USER.PSWD_LOCK_YMD IS '비밀번호잠금일자';
COMMENT ON COLUMN APFS.TMP_USER.PSWD_ERR_CNT IS '비밀번호오류수';
COMMENT ON COLUMN APFS.TMP_USER.PSWD_CHG_YMD IS '비밀번호변경일자';
COMMENT ON COLUMN APFS.TMP_USER.PSWD_NEXT_YMD IS '비밀번호다음일자';
COMMENT ON COLUMN APFS.TMP_USER.LST_LGN_DT IS '마지막로그인일시';
COMMENT ON COLUMN APFS.TMP_USER.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.TMP_USER.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.TMP_USER.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.TMP_USER.MDFCN_YMD IS '수정일자';

CREATE TABLE APFS.TMP_OAUTH (
	USER_NO VARCHAR(20) NOT NULL,
	OATH_CD VARCHAR(20) NOT NULL,
	OATH_ID VARCHAR(50),
	USER_NM VARCHAR(40),
	EMAIL VARCHAR(100),
	MOBILE VARCHAR(20),
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (USER_NO, OATH_CD)
);
COMMENT ON TABLE  APFS.TMP_OAUTH IS '사용자정보';
COMMENT ON COLUMN APFS.TMP_OAUTH.USER_NO IS '사용자번호';
COMMENT ON COLUMN APFS.TMP_OAUTH.OATH_CD IS 'OAUTH 서비스코드';
COMMENT ON COLUMN APFS.TMP_OAUTH.USER_NM IS '사용자명';
COMMENT ON COLUMN APFS.TMP_OAUTH.OATH_ID IS 'OAUTH 식별ID';
COMMENT ON COLUMN APFS.TMP_OAUTH.EMAIL IS '이메일';
COMMENT ON COLUMN APFS.TMP_OAUTH.MOBILE IS '휴대전화번호';
COMMENT ON COLUMN APFS.TMP_OAUTH.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.TMP_OAUTH.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.TMP_OAUTH.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.TMP_OAUTH.MDFCN_YMD IS '수정일자';

CREATE TABLE APFS.TMP_MAIL_HST (
	SN INTEGER NOT NULL,
	USER_NO VARCHAR(20),
	TO_ADDR VARCHAR(50),
	TO_NAME VARCHAR(40),
	FR_ADDR VARCHAR(50),
	FR_NAME VARCHAR(40),
	SUBJECT VARCHAR(200),
	CONTENT TEXT,
	TEMPLATE VARCHAR(30),
	SEND_DT DATE,
	SEND_CD VARCHAR(20),
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (SN)
);
COMMENT ON TABLE  APFS.TMP_MAIL_HST IS 'TMP_MAIL_HST';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.SN IS '일련번호';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.USER_NO IS '사용자번호';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.SEND_DT IS '발송일시';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.SEND_CD IS '발송결과코드';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.SUBJECT IS '메일제목';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.CONTENT IS '메일내용';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.TEMPLATE IS '템플릿파일';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.TO_ADDR IS '수신이메일주소';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.TO_NAME IS '수신자명';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.FR_ADDR IS '발신이메일주소';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.FR_NAME IS '발신자명';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.MDFCN_YMD IS '수정일자';


CREATE TABLE APFS.TMP_FILE (
	SN NUMERIC(10,0) NOT NULL,
	DTY_SE_CD VARCHAR(10),
	DCMT_NO VARCHAR(10),
	FILE_PATH VARCHAR(200),
	STRG_FILE_NM VARCHAR(100),
	FILE_NM VARCHAR(200),
	FILE_SZ NUMERIC(14,0),
	DEL_YN CHAR(1),
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (SN)
);
COMMENT ON TABLE APFS.TMP_FILE IS '공통첨부파일';
COMMENT ON COLUMN APFS.TMP_FILE.SN IS '일련번호';
COMMENT ON COLUMN APFS.TMP_FILE.DTY_SE_CD IS '구분코드';
COMMENT ON COLUMN APFS.TMP_FILE.DCMT_NO IS '문서번호';
COMMENT ON COLUMN APFS.TMP_FILE.FILE_PATH IS '파일경로';
COMMENT ON COLUMN APFS.TMP_FILE.STRG_FILE_NM IS '저장파일명';
COMMENT ON COLUMN APFS.TMP_FILE.FILE_NM IS '파일명';
COMMENT ON COLUMN APFS.TMP_FILE.FILE_SZ IS '파일크기';
COMMENT ON COLUMN APFS.TMP_FILE.DEL_YN IS '삭제여부';
COMMENT ON COLUMN APFS.TMP_FILE.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.TMP_FILE.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.TMP_FILE.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.TMP_FILE.MDFCN_YMD IS '수정일자';

CREATE TABLE APFS.TMP_APLY_FILE (
	SN NUMERIC(10,0) NOT NULL,
	DTY_SE_CD VARCHAR(10),
	DCMT_NO VARCHAR(10),
	DTL_DCMT_NO NUMERIC(10,0),
	PAPE_CD VARCHAR(10),
	FILE_PATH VARCHAR(200),
	STRG_FILE_NM VARCHAR(100),
	FILE_NM VARCHAR(200),
	FILE_SZ NUMERIC(14,0),
	PRCS_STUS_CD VARCHAR(2),
	PRCS_CN VARCHAR(2000),
	DEL_YN CHAR(1),
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	MNGR_REG_YN CHAR(1),
	PRIMARY KEY (SN)
);
COMMENT ON TABLE APFS.TMP_APLY_FILE IS '신청첨부파일';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.SN IS '일련번호';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.DTY_SE_CD IS '업무구분코드';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.DCMT_NO IS '문서번호';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.DTL_DCMT_NO IS '세부문서번호';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.PAPE_CD IS '서류코드';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.FILE_PATH IS '파일경로';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.STRG_FILE_NM IS '저장파일명';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.FILE_NM IS '파일명';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.FILE_SZ IS '파일크기';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.PRCS_STUS_CD IS '처리상태코드';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.PRCS_CN IS '처리내용';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.DEL_YN IS '삭제여부';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.MDFCN_YMD IS '수정일자';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.MNGR_REG_YN IS '관리자등록여부';

CREATE TABLE APFS.TMP_PAPE_CODE (
	PAPE_CD VARCHAR(10) NOT NULL,
	UP_PAPE_CD VARCHAR(10) NOT NULL,
	PAPE_NM VARCHAR(100),
	PAPE_DTY_SE_CD VARCHAR(10),
	LIMT_CNT NUMERIC(2,0),
	ESNTL_YN CHAR(1),
	CD_ORDR NUMERIC(5,0),
	FILE_NM VARCHAR(200),
	FILE_PATH VARCHAR(200),
	DOWN_CNT NUMERIC(10),
	DOWN_TRGT_YN CHAR(1),
	USE_YN CHAR(1),
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (PAPE_CD, UP_PAPE_CD)
);
COMMENT ON TABLE APFS.TMP_PAPE_CODE IS '서류코드관리';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.PAPE_CD IS '서류코드';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.UP_PAPE_CD IS '상위서류코드';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.PAPE_NM IS '서류명';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.PAPE_DTY_SE_CD IS '업무구분코드';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.LIMT_CNT IS '제한수';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.ESNTL_YN IS '필수여부';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.CD_ORDR IS '코드순서';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.FILE_NM IS '파일명';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.FILE_PATH IS '파일경로';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.DOWN_CNT IS '다운로드수';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.DOWN_TRGT_YN IS '다운로드대상여부';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.USE_YN IS '사용여부';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.MDFCN_YMD IS '수정일자';

CREATE TABLE IF NOT EXISTS apfs.TMP_ENP
(
    kedcd character varying(10) NOT NULL,
    enp_nm character varying(100) ,
    enp_nm_trd character varying(100) ,
    enp_nm_eng character varying(200) ,
    enp_typ character(1) ,
    enp_sze character varying(2) ,
    grdt_pln_dt character varying(8) ,
    enp_fcd character varying(2) ,
    estb_fcd character varying(2) ,
    enp_scd character varying(2) ,
    enp_scd_chg_dt character varying(8) ,
    pubi_fcd character varying(2) ,
    venp_yn character varying(1) ,
    enp_form_fr character(1) ,
    bzc_cd character varying(6) ,
    fs_bzc_cd character varying(2) ,
    grp_cd character varying(4) ,
    grp_nm character varying(50) ,
    cono_pid character varying(13) ,
    estb_dt character varying(8) ,
    ipo_cd character(1) ,
    trdbz_rpt_no character varying(10) ,
    list_dt character varying(8) ,
    dlist_dt character varying(8) ,
    mtx_bnk_cd character varying(7) ,
    mtx_bnk_nm character varying(70) ,
    ovd_tx_bnk_cd character varying(7) ,
    ovd_tx_bnk_nm character varying(70) ,
    acct_eddt character varying(4) ,
    hpage_url character varying(50) ,
    email character varying(40) ,
    std_dt character varying(8) ,
    bzno character varying(10) ,
    loc_zip character varying(6) ,
    loc_addra character varying(200) ,
    loc_addrb character varying(200) ,
    tel_no character varying(20) ,
    fax_no character varying(20) ,
    laborer_sum numeric(13,0),
    pd_nm character varying(100) ,
    ksic9_bzc_cd character varying(6) ,
    rel_kedcd character varying(10) ,
    rel_estb_dt character varying(8) ,
    loc_rdnm_zip character varying(6) ,
    loc_rdnm_addra character varying(100) ,
    loc_rdnm_addrb character varying(200) ,
    loc_rdnm_addrb_conf_yn character varying(1) ,
    loc_addrb_conf_yn character varying(1) ,
    CONSTRAINT TMP_ENP_KEY PRIMARY KEY (kedcd)
);

COMMENT ON TABLE apfs.TMP_ENP
    IS '업체개요';

COMMENT ON COLUMN APFS.TMP_ENP.kedcd
    IS 'KED코드';

COMMENT ON COLUMN APFS.TMP_ENP.enp_nm
    IS '기업체명';

COMMENT ON COLUMN APFS.TMP_ENP.enp_nm_trd
    IS '기업체TradeName';

COMMENT ON COLUMN APFS.TMP_ENP.enp_nm_eng
    IS '기업체명 영문';

COMMENT ON COLUMN APFS.TMP_ENP.enp_typ
    IS '기업유형';

COMMENT ON COLUMN APFS.TMP_ENP.enp_sze
    IS '기업규모';

COMMENT ON COLUMN APFS.TMP_ENP.grdt_pln_dt
    IS '졸업예정일';

COMMENT ON COLUMN APFS.TMP_ENP.enp_fcd
    IS '기업형태코드';

COMMENT ON COLUMN APFS.TMP_ENP.estb_fcd
    IS '설립형태';

COMMENT ON COLUMN APFS.TMP_ENP.enp_scd
    IS '기업상태';

COMMENT ON COLUMN APFS.TMP_ENP.enp_scd_chg_dt
    IS '기업상태변동일';

COMMENT ON COLUMN APFS.TMP_ENP.pubi_fcd
    IS '정부및공공기관구분';

COMMENT ON COLUMN APFS.TMP_ENP.venp_yn
    IS '벤쳐기업유무';

COMMENT ON COLUMN APFS.TMP_ENP.enp_form_fr
    IS '기업형태앞뒤구분';

COMMENT ON COLUMN APFS.TMP_ENP.bzc_cd
    IS '업종코드';

COMMENT ON COLUMN APFS.TMP_ENP.fs_bzc_cd
    IS '재무업종코드';

COMMENT ON COLUMN APFS.TMP_ENP.grp_cd
    IS '그룹코드';

COMMENT ON COLUMN APFS.TMP_ENP.grp_nm
    IS '그룹명';

COMMENT ON COLUMN APFS.TMP_ENP.cono_pid
    IS '법인_주민등록번호';

COMMENT ON COLUMN APFS.TMP_ENP.estb_dt
    IS '설립일자';

COMMENT ON COLUMN APFS.TMP_ENP.ipo_cd
    IS '기업공개코드';

COMMENT ON COLUMN APFS.TMP_ENP.trdbz_rpt_no
    IS '무역업신고번호';

COMMENT ON COLUMN APFS.TMP_ENP.list_dt
    IS '상장일자';

COMMENT ON COLUMN APFS.TMP_ENP.dlist_dt
    IS '상장폐지일자';

COMMENT ON COLUMN APFS.TMP_ENP.mtx_bnk_cd
    IS '주거래여신기관코드';

COMMENT ON COLUMN APFS.TMP_ENP.mtx_bnk_nm
    IS '주거래여신기관명';

COMMENT ON COLUMN APFS.TMP_ENP.ovd_tx_bnk_cd
    IS '당좌거래은행코드';

COMMENT ON COLUMN APFS.TMP_ENP.ovd_tx_bnk_nm
    IS '당좌거래은행명';

COMMENT ON COLUMN APFS.TMP_ENP.acct_eddt
    IS '결산기준월일';

COMMENT ON COLUMN APFS.TMP_ENP.hpage_url
    IS '홈페이지';

COMMENT ON COLUMN APFS.TMP_ENP.email
    IS '이메일';

COMMENT ON COLUMN APFS.TMP_ENP.std_dt
    IS '정보기준일자';

COMMENT ON COLUMN APFS.TMP_ENP.bzno
    IS '사업자번호';

COMMENT ON COLUMN APFS.TMP_ENP.loc_zip
    IS '소재지우편번호';

COMMENT ON COLUMN APFS.TMP_ENP.loc_addra
    IS '소재지우편번호주소';

COMMENT ON COLUMN APFS.TMP_ENP.loc_addrb
    IS '소재지_나머지주소';

COMMENT ON COLUMN APFS.TMP_ENP.tel_no
    IS '전화번호';

COMMENT ON COLUMN APFS.TMP_ENP.fax_no
    IS '팩스번호';

COMMENT ON COLUMN APFS.TMP_ENP.laborer_sum
    IS '상시근로자수(합계)';

COMMENT ON COLUMN APFS.TMP_ENP.pd_nm
    IS '제품명';

COMMENT ON COLUMN APFS.TMP_ENP.ksic9_bzc_cd
    IS '업종코드';

COMMENT ON COLUMN APFS.TMP_ENP.rel_kedcd
    IS '관련기업KED코드';

COMMENT ON COLUMN APFS.TMP_ENP.rel_estb_dt
    IS '관련기업설립일';

COMMENT ON COLUMN APFS.TMP_ENP.loc_rdnm_zip
    IS '도로명소재지우편번호';

COMMENT ON COLUMN APFS.TMP_ENP.loc_rdnm_addra
    IS '도로명소재지우편번호주소';

COMMENT ON COLUMN APFS.TMP_ENP.loc_rdnm_addrb
    IS '도로명소재지우편번호이하주소';

COMMENT ON COLUMN APFS.TMP_ENP.loc_rdnm_addrb_conf_yn
    IS '도로명소재지주소확인여부';

COMMENT ON COLUMN APFS.TMP_ENP.loc_addrb_conf_yn
    IS '소재지주소확인여부';

