
/* Drop Tables */

DROP TABLE IF EXISTS TB_CODE_KO;
DROP TABLE IF EXISTS TB_ENT_FILE;
DROP TABLE IF EXISTS TB_ENT_RLM;
DROP TABLE IF EXISTS TB_GRP_AUTH;
DROP TABLE IF EXISTS TB_GRP_USR;
DROP TABLE IF EXISTS TB_USER;
DROP TABLE IF EXISTS TB_ENT;
DROP TABLE IF EXISTS TB_ENT_INQ_HST;
DROP TABLE IF EXISTS TB_FNNR_CODE_KO;
DROP TABLE IF EXISTS TB_GRP_MENU;
DROP TABLE IF EXISTS TB_INVTRLM_CODE;
DROP TABLE IF EXISTS TB_SGG;




/* Create Tables */

-- 공통코드(KODATA)
CREATE TABLE TB_CODE_KO
(
	SN numeric(10) NOT NULL,
	CD_ID varchar(20) NOT NULL,
	UP_CD_ID varchar(20) NOT NULL,
	CD_NM varchar(200),
	CD_CTT varchar(500),
	GUIDANCE_MTTR varchar(1000),
	KD_CD_TY varchar(20),
	SYS_CD_TY varchar(20),
	SYS_CD_ID varchar(20),
	SYS_CD_NM varchar(200),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 업체정보
CREATE TABLE TB_ENT
(
	BZENTY_NO varchar(20) NOT NULL,
	UP_BZENTY_NO varchar(20),
	BZENTY_SE_CD varchar(3),
	BRNO char(10) UNIQUE,
	CRNO char(13),
	BZENTY_NM varchar(100),
	RPRSV_NM varchar(100),
	RPRSV_BRDT char(8),
	RPRSV_SEXDSTN char(1),
	FNDN_YMD varchar(8),
	RPRS_TELNO varchar(20),
	FXNO varchar(20),
	TPBIZ_CD varchar(10),
	TPBIZ_NM varchar(200),
	BZENTY_TYPE_CD varchar(3),
	BZENTY_STLE_CD varchar(3),
	BZENTY_SCALE_CD varchar(3),
	INVT_HOPE_AMT numeric(15),
	EML_ADDR varchar(100),
	HMPG_ADDR varchar(500),
	ZIP char(5),
	LCTN_ADDR varchar(200),
	LCTN_DADDR varchar(200),
	EMP_CNT numeric(10),
	GROUP_CD varchar(20),
	KD_CD varchar(10),
	DIRECT_INPT_YN char(1),
	RMRK4 varchar(300),
	RMRK5 varchar(300),
	MNGR_MEMO varchar(300),
	APRV_YMD timestamp,
	RJCT_YMD timestamp,
	USE_STTS_CD varchar(3),
	LCINFO point,
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (BZENTY_NO)
) WITHOUT OIDS;


-- 업체첨부파일
CREATE TABLE TB_ENT_FILE
(
	BZENTY_NO varchar(20) NOT NULL,
	SN numeric(10) NOT NULL,
	DOC_SE_CD varchar(3),
	FILE_NM varchar(200),
	STRG_FILE_NM varchar(200),
	FILE_PATH varchar(200),
	FILE_SZ numeric(14),
	RPRS_YN char(1),
	DEL_YN char(1),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (BZENTY_NO, SN)
) WITHOUT OIDS;


-- 업체조회이력
CREATE TABLE TB_ENT_INQ_HST
(
	SN numeric(10) NOT NULL,
	BZENTY_NO varchar(20),
	USER_NO varchar(20),
	INQ_YMD varchar(8),
	REG_YMD timestamp,
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 업체분야정보
CREATE TABLE TB_ENT_RLM
(
	BZENTY_NO varchar(20) NOT NULL,
	FLD_SE_CD varchar(3) NOT NULL,
	FLD_CD varchar(10) NOT NULL,
	FLD_CN varchar(4000),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (BZENTY_NO, FLD_SE_CD, FLD_CD)
) WITHOUT OIDS;


-- 재무계정코드(KODATA)
CREATE TABLE TB_FNNR_CODE_KO
(
	FNNR_ACNT_CD varchar(10) NOT NULL,
	FNNR_SE_CD varchar(3),
	FNNR_ACNT_NM varchar(100),
	FNNR_ACNT_ENG_NM varchar(100),
	FNNR_CD_STEP numeric(3),
	FNNR_CD_ORDR numeric(5),
	FNNR_TPBIZ_CD varchar(10),
	FNNR_INFO_SE_CD varchar(10),
	UNIT varchar(20),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (FNNR_ACNT_CD)
) WITHOUT OIDS;


-- 그룹권한관리
CREATE TABLE TB_GRP_AUTH
(
	USER_NO varchar(20) NOT NULL,
	MENU_ID varchar(20) NOT NULL,
	GROUP_AUTHRT_CD varchar(10),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (USER_NO, MENU_ID)
) WITHOUT OIDS;


-- 그룹메뉴관리
CREATE TABLE TB_GRP_MENU
(
	MENU_ID varchar(20) NOT NULL,
	MENU_NM varchar(300),
	TRGT_URL varchar(500),
	SYS_AUTHRT_INFO varchar(300),
	RPRS_YN char(1),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (MENU_ID)
) WITHOUT OIDS;


-- 그룹사용자관리
CREATE TABLE TB_GRP_USR
(
	USER_NO varchar(20) NOT NULL,
	RPRS_YN char(1),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (USER_NO)
) WITHOUT OIDS;


-- 투자분야코드관리
CREATE TABLE TB_INVTRLM_CODE
(
	INVT_FLD_CD varchar(10) NOT NULL,
	INVT_FLD_NM varchar(100),
	INVT_FLD_CN varchar(1000),
	ITM_KWRD varchar(300),
	USE_BGNG_YMD varchar(8),
	USE_END_YMD varchar(8),
	CD_ORDR numeric(5),
	USE_YN char(1),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (INVT_FLD_CD)
) WITHOUT OIDS;


-- 시군구정보
CREATE TABLE TB_SGG
(
	SGG_NO varchar(10) NOT NULL,
	SGG_NM varchar(100),
	SGG_LCINFO point,
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (SGG_NO)
) WITHOUT OIDS;


-- 사용자정보
CREATE TABLE TB_USER
(
	USER_NO varchar(20) NOT NULL,
	BZENTY_NO varchar(20),
	USER_ID varchar(50) UNIQUE,
	USER_NM varchar(40),
	PSWD varchar(100),
	EML_ADDR varchar(100),
	TELNO varchar(11),
	MBL_TELNO varchar(20),
	BRDT char(8),
	ZIP char(5),
	ADDR varchar(200),
	DADDR varchar(200),
	SEXDSTN char(1),
	DEPT_CD varchar(30),
	DEPT_NM varchar(200),
	EMPL_NO varchar(20),
	IDNTF_ID varchar(50),
	LGN_SE_CD varchar(3),
	JOIN_YMD varchar(8),
	WHDWL_YMD varchar(8),
	CNTN_PSBLTY_IP_ADDR varchar(80),
	PSWD_LOCK_YMD varchar(8),
	PSWD_ERR_CNT numeric(3),
	PSWD_CHG_YMD varchar(8),
	PSWD_NEXT_YMD varchar(8),
	LAST_LGN_DT timestamp,
	MOBLPHON_RCPTN_AGRE_YN char(1),
	PRVC_CLCT_AGRE_YN char(1),
	THPTY_PVSN_AGRE_YN char(1),
	USE_STTS_CD varchar(3),
	TEST_USE_YN char(1),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (USER_NO)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE TB_ENT_FILE
	ADD FOREIGN KEY (BZENTY_NO)
	REFERENCES TB_ENT (BZENTY_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_ENT_RLM
	ADD FOREIGN KEY (BZENTY_NO)
	REFERENCES TB_ENT (BZENTY_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_USER
	ADD FOREIGN KEY (BZENTY_NO)
	REFERENCES TB_ENT (BZENTY_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_GRP_AUTH
	ADD FOREIGN KEY (MENU_ID)
	REFERENCES TB_GRP_MENU (MENU_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_GRP_AUTH
	ADD FOREIGN KEY (USER_NO)
	REFERENCES TB_GRP_USR (USER_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_GRP_USR
	ADD FOREIGN KEY (USER_NO)
	REFERENCES TB_USER (USER_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON TABLE TB_CODE_KO IS '공통코드(KODATA)';
COMMENT ON COLUMN TB_CODE_KO.SN IS '일련번호';
COMMENT ON COLUMN TB_CODE_KO.CD_ID IS '코드ID';
COMMENT ON COLUMN TB_CODE_KO.UP_CD_ID IS '상위코드ID';
COMMENT ON COLUMN TB_CODE_KO.CD_NM IS '코드명';
COMMENT ON COLUMN TB_CODE_KO.CD_CTT IS '코드내용';
COMMENT ON COLUMN TB_CODE_KO.GUIDANCE_MTTR IS '안내사항';
COMMENT ON COLUMN TB_CODE_KO.KD_CD_TY IS 'KODATA코드타입';
COMMENT ON COLUMN TB_CODE_KO.SYS_CD_TY IS '시스템코드타입';
COMMENT ON COLUMN TB_CODE_KO.SYS_CD_ID IS '시스템코드ID';
COMMENT ON COLUMN TB_CODE_KO.SYS_CD_NM IS '시스템코드명';
COMMENT ON COLUMN TB_CODE_KO.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_CODE_KO.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_CODE_KO.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_CODE_KO.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_ENT IS '업체정보';
COMMENT ON COLUMN TB_ENT.BZENTY_NO IS '업체번호';
COMMENT ON COLUMN TB_ENT.UP_BZENTY_NO IS '상위업체번호';
COMMENT ON COLUMN TB_ENT.BZENTY_SE_CD IS '업체구분코드';
COMMENT ON COLUMN TB_ENT.BRNO IS '사업자등록번호';
COMMENT ON COLUMN TB_ENT.CRNO IS '법인등록번호';
COMMENT ON COLUMN TB_ENT.BZENTY_NM IS '업체명';
COMMENT ON COLUMN TB_ENT.RPRSV_NM IS '대표자명';
COMMENT ON COLUMN TB_ENT.RPRSV_BRDT IS '대표자생년월일';
COMMENT ON COLUMN TB_ENT.RPRSV_SEXDSTN IS '대표자성별';
COMMENT ON COLUMN TB_ENT.FNDN_YMD IS '설립일자';
COMMENT ON COLUMN TB_ENT.RPRS_TELNO IS '대표전화번호';
COMMENT ON COLUMN TB_ENT.FXNO IS '팩스번호';
COMMENT ON COLUMN TB_ENT.TPBIZ_CD IS '업종코드';
COMMENT ON COLUMN TB_ENT.TPBIZ_NM IS '업종명';
COMMENT ON COLUMN TB_ENT.BZENTY_TYPE_CD IS '업체유형코드';
COMMENT ON COLUMN TB_ENT.BZENTY_STLE_CD IS '업체형태코드';
COMMENT ON COLUMN TB_ENT.BZENTY_SCALE_CD IS '업체규모코드';
COMMENT ON COLUMN TB_ENT.INVT_HOPE_AMT IS '투자희망금액';
COMMENT ON COLUMN TB_ENT.EML_ADDR IS '이메일주소';
COMMENT ON COLUMN TB_ENT.HMPG_ADDR IS '홈페이지주소';
COMMENT ON COLUMN TB_ENT.ZIP IS '우편번호';
COMMENT ON COLUMN TB_ENT.LCTN_ADDR IS '소재지주소';
COMMENT ON COLUMN TB_ENT.LCTN_DADDR IS '소재지상세주소';
COMMENT ON COLUMN TB_ENT.EMP_CNT IS '직원수';
COMMENT ON COLUMN TB_ENT.GROUP_CD IS '그룹코드';
COMMENT ON COLUMN TB_ENT.KD_CD IS 'KODATA코드';
COMMENT ON COLUMN TB_ENT.DIRECT_INPT_YN IS '직접입력여부';
COMMENT ON COLUMN TB_ENT.RMRK4 IS '비고4';
COMMENT ON COLUMN TB_ENT.RMRK5 IS '비고5';
COMMENT ON COLUMN TB_ENT.MNGR_MEMO IS '관리자메모';
COMMENT ON COLUMN TB_ENT.APRV_YMD IS '승인일자';
COMMENT ON COLUMN TB_ENT.RJCT_YMD IS '반려일자';
COMMENT ON COLUMN TB_ENT.USE_STTS_CD IS '사용상태코드';
COMMENT ON COLUMN TB_ENT.LCINFO IS '위치정보';
COMMENT ON COLUMN TB_ENT.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_ENT.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_ENT.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_ENT.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_ENT_FILE IS '업체첨부파일';
COMMENT ON COLUMN TB_ENT_FILE.BZENTY_NO IS '업체번호';
COMMENT ON COLUMN TB_ENT_FILE.SN IS '일련번호';
COMMENT ON COLUMN TB_ENT_FILE.DOC_SE_CD IS '문서구분코드';
COMMENT ON COLUMN TB_ENT_FILE.FILE_NM IS '파일명';
COMMENT ON COLUMN TB_ENT_FILE.STRG_FILE_NM IS '저장파일명';
COMMENT ON COLUMN TB_ENT_FILE.FILE_PATH IS '파일경로';
COMMENT ON COLUMN TB_ENT_FILE.FILE_SZ IS '파일크기';
COMMENT ON COLUMN TB_ENT_FILE.RPRS_YN IS '대표여부';
COMMENT ON COLUMN TB_ENT_FILE.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TB_ENT_FILE.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_ENT_FILE.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_ENT_FILE.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_ENT_FILE.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_ENT_INQ_HST IS '업체조회이력';
COMMENT ON COLUMN TB_ENT_INQ_HST.SN IS '일련번호';
COMMENT ON COLUMN TB_ENT_INQ_HST.BZENTY_NO IS '업체번호';
COMMENT ON COLUMN TB_ENT_INQ_HST.USER_NO IS '사용자번호';
COMMENT ON COLUMN TB_ENT_INQ_HST.INQ_YMD IS '조회일자';
COMMENT ON COLUMN TB_ENT_INQ_HST.REG_YMD IS '등록일자';
COMMENT ON TABLE TB_ENT_RLM IS '업체분야정보';
COMMENT ON COLUMN TB_ENT_RLM.BZENTY_NO IS '업체번호';
COMMENT ON COLUMN TB_ENT_RLM.FLD_SE_CD IS '분야구분코드';
COMMENT ON COLUMN TB_ENT_RLM.FLD_CD IS '분야코드';
COMMENT ON COLUMN TB_ENT_RLM.FLD_CN IS '분야내용';
COMMENT ON COLUMN TB_ENT_RLM.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_ENT_RLM.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_ENT_RLM.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_ENT_RLM.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_FNNR_CODE_KO IS '재무계정코드(KODATA)';
COMMENT ON COLUMN TB_FNNR_CODE_KO.FNNR_ACNT_CD IS '재무계정코드';
COMMENT ON COLUMN TB_FNNR_CODE_KO.FNNR_SE_CD IS '재무구분코드';
COMMENT ON COLUMN TB_FNNR_CODE_KO.FNNR_ACNT_NM IS '재무계정명';
COMMENT ON COLUMN TB_FNNR_CODE_KO.FNNR_ACNT_ENG_NM IS '재무계정영문명';
COMMENT ON COLUMN TB_FNNR_CODE_KO.FNNR_CD_STEP IS '계정코드단계';
COMMENT ON COLUMN TB_FNNR_CODE_KO.FNNR_CD_ORDR IS '계정코드순서';
COMMENT ON COLUMN TB_FNNR_CODE_KO.FNNR_TPBIZ_CD IS '재무업종코드';
COMMENT ON COLUMN TB_FNNR_CODE_KO.FNNR_INFO_SE_CD IS '재무정보구분코드';
COMMENT ON COLUMN TB_FNNR_CODE_KO.UNIT IS '단위';
COMMENT ON COLUMN TB_FNNR_CODE_KO.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_FNNR_CODE_KO.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_FNNR_CODE_KO.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_FNNR_CODE_KO.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_GRP_AUTH IS '그룹권한관리';
COMMENT ON COLUMN TB_GRP_AUTH.USER_NO IS '사용자번호';
COMMENT ON COLUMN TB_GRP_AUTH.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN TB_GRP_AUTH.GROUP_AUTHRT_CD IS '그룹권한코드';
COMMENT ON COLUMN TB_GRP_AUTH.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_GRP_AUTH.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_GRP_AUTH.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_GRP_AUTH.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_GRP_MENU IS '그룹메뉴관리';
COMMENT ON COLUMN TB_GRP_MENU.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN TB_GRP_MENU.MENU_NM IS '메뉴명';
COMMENT ON COLUMN TB_GRP_MENU.TRGT_URL IS '타겟URL';
COMMENT ON COLUMN TB_GRP_MENU.SYS_AUTHRT_INFO IS '시스템권한정보';
COMMENT ON COLUMN TB_GRP_MENU.RPRS_YN IS '대표여부';
COMMENT ON COLUMN TB_GRP_MENU.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_GRP_MENU.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_GRP_MENU.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_GRP_MENU.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_GRP_USR IS '그룹사용자관리';
COMMENT ON COLUMN TB_GRP_USR.USER_NO IS '사용자번호';
COMMENT ON COLUMN TB_GRP_USR.RPRS_YN IS '대표여부';
COMMENT ON COLUMN TB_GRP_USR.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_GRP_USR.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_GRP_USR.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_GRP_USR.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_INVTRLM_CODE IS '투자분야코드관리';
COMMENT ON COLUMN TB_INVTRLM_CODE.INVT_FLD_CD IS '투자분야코드';
COMMENT ON COLUMN TB_INVTRLM_CODE.INVT_FLD_NM IS '투자분야명';
COMMENT ON COLUMN TB_INVTRLM_CODE.INVT_FLD_CN IS '투자분야내용';
COMMENT ON COLUMN TB_INVTRLM_CODE.ITM_KWRD IS '아이템키워드';
COMMENT ON COLUMN TB_INVTRLM_CODE.USE_BGNG_YMD IS '사용시작일자';
COMMENT ON COLUMN TB_INVTRLM_CODE.USE_END_YMD IS '사용종료일자';
COMMENT ON COLUMN TB_INVTRLM_CODE.CD_ORDR IS '코드순서';
COMMENT ON COLUMN TB_INVTRLM_CODE.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_INVTRLM_CODE.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_INVTRLM_CODE.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_INVTRLM_CODE.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_INVTRLM_CODE.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_SGG IS '시군구정보';
COMMENT ON COLUMN TB_SGG.SGG_NO IS '시군구번호';
COMMENT ON COLUMN TB_SGG.SGG_NM IS '시군구명';
COMMENT ON COLUMN TB_SGG.SGG_LCINFO IS '시군구위치정보';
COMMENT ON COLUMN TB_SGG.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_SGG.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_SGG.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_SGG.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_USER IS '사용자정보';
COMMENT ON COLUMN TB_USER.USER_NO IS '사용자번호';
COMMENT ON COLUMN TB_USER.BZENTY_NO IS '업체번호';
COMMENT ON COLUMN TB_USER.USER_ID IS '사용자ID';
COMMENT ON COLUMN TB_USER.USER_NM IS '사용자명';
COMMENT ON COLUMN TB_USER.PSWD IS '비밀번호';
COMMENT ON COLUMN TB_USER.EML_ADDR IS '이메일주소';
COMMENT ON COLUMN TB_USER.TELNO IS '전화번호';
COMMENT ON COLUMN TB_USER.MBL_TELNO IS '휴대전화번호';
COMMENT ON COLUMN TB_USER.BRDT IS '생년월일';
COMMENT ON COLUMN TB_USER.ZIP IS '우편번호';
COMMENT ON COLUMN TB_USER.ADDR IS '주소';
COMMENT ON COLUMN TB_USER.DADDR IS '상세주소';
COMMENT ON COLUMN TB_USER.SEXDSTN IS '성별';
COMMENT ON COLUMN TB_USER.DEPT_CD IS '부서코드';
COMMENT ON COLUMN TB_USER.DEPT_NM IS '부서명';
COMMENT ON COLUMN TB_USER.EMPL_NO IS '사원번호';
COMMENT ON COLUMN TB_USER.IDNTF_ID IS '식별ID';
COMMENT ON COLUMN TB_USER.LGN_SE_CD IS '로그인구분코드';
COMMENT ON COLUMN TB_USER.JOIN_YMD IS '가입일자';
COMMENT ON COLUMN TB_USER.WHDWL_YMD IS '탈퇴일자';
COMMENT ON COLUMN TB_USER.CNTN_PSBLTY_IP_ADDR IS '접속가능IP주소';
COMMENT ON COLUMN TB_USER.PSWD_LOCK_YMD IS '비밀번호잠금일자';
COMMENT ON COLUMN TB_USER.PSWD_ERR_CNT IS '비밀번호오류수';
COMMENT ON COLUMN TB_USER.PSWD_CHG_YMD IS '비밀번호변경일자';
COMMENT ON COLUMN TB_USER.PSWD_NEXT_YMD IS '비밀번호다음일자';
COMMENT ON COLUMN TB_USER.LAST_LGN_DT IS '마지막로그인일시';
COMMENT ON COLUMN TB_USER.MOBLPHON_RCPTN_AGRE_YN IS '휴대전화수신동의여부';
COMMENT ON COLUMN TB_USER.PRVC_CLCT_AGRE_YN IS '개인정보수집동의여부';
COMMENT ON COLUMN TB_USER.THPTY_PVSN_AGRE_YN IS '제3자제공동의여부';
COMMENT ON COLUMN TB_USER.USE_STTS_CD IS '사용상태코드';
COMMENT ON COLUMN TB_USER.TEST_USE_YN IS '시험사용여부';
COMMENT ON COLUMN TB_USER.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_USER.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_USER.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_USER.MDFCN_YMD IS '수정일자';



