
/* Drop Tables */

DROP TABLE IF EXISTS TB_BKMK_INFO;
DROP TABLE IF EXISTS TB_OPINION_IR;
DROP TABLE IF EXISTS TB_EVENT_ENT;
DROP TABLE IF EXISTS TB_EVENT_INVT;
DROP TABLE IF EXISTS TB_EVENT_MNG;
DROP TABLE IF EXISTS TB_FUND_INVSTR;
DROP TABLE IF EXISTS TB_FUND_SPRT;
DROP TABLE IF EXISTS TB_FUND_INFO;
DROP TABLE IF EXISTS TB_MTCHG_STNG;
DROP TABLE IF EXISTS TB_MTG_APLY;
DROP TABLE IF EXISTS TB_SPRT_BIZ;
DROP TABLE IF EXISTS TB_SPRT_ULD;




/* Create Tables */

-- 북마크정보
CREATE TABLE TB_BKMK_INFO
(
	SN numeric(10) NOT NULL,
	BZENTY_NO varchar(20) NOT NULL,
	TRGT_BZENTY_NO varchar(20),
	DOC_NO varchar(20),
	BKMK_SE_CD varchar(3),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 행사참여경영체
CREATE TABLE TB_EVENT_ENT
(
	EVNT_PARTCPTN_NO varchar(20) NOT NULL,
	EVNT_NO varchar(20) NOT NULL,
	BZENTY_NO varchar(20),
	BRNO char(10),
	BZENTY_NM varchar(100),
	RPRSV_NM varchar(20),
	TELNO varchar(11),
	EML_ADDR varchar(100),
	MAIN_BIZ_CN varchar(2000),
	INQ_CNT numeric(10),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (EVNT_PARTCPTN_NO)
) WITHOUT OIDS;


-- 행사참여투자자
CREATE TABLE TB_EVENT_INVT
(
	EVNT_NO varchar(20) NOT NULL,
	BZENTY_NO varchar(20) NOT NULL,
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (EVNT_NO, BZENTY_NO)
) WITHOUT OIDS;


-- 행사관리(투자설명회)
CREATE TABLE TB_EVENT_MNG
(
	EVNT_NO varchar(20) NOT NULL,
	EVNT_NM varchar(100),
	EVNT_CN text,
	EVNT_BGNG_YMD varchar(8),
	EVNT_END_YMD varchar(8),
	EVNT_YR char(4),
	USE_YN char(1),
	DEL_YN char(1),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (EVNT_NO)
) WITHOUT OIDS;


-- 펀드정보(모태펀드)
CREATE TABLE TB_FUND_INFO
(
	FUND_NO varchar(20) NOT NULL,
	FUND_NM varchar(100),
	FUND_CN varchar(4000),
	INVT_FLD_CD varchar(10),
	FUND_OPER_SCALE numeric(14),
	MAKE_YR char(4),
	ORGZ_YMD varchar(8),
	INVT_BGNG_YMD varchar(8),
	INVT_END_YMD varchar(8),
	MXTR_STTS_CD varchar(3),
	MMBS1 varchar(100),
	MMBS2 varchar(100),
	MMBS3 varchar(100),
	MMBS4 varchar(100),
	MMBS5 varchar(100),
	RPRS_TELNO varchar(11),
	RPRS_HMPG_ADDR varchar(500),
	USE_YN char(1),
	DEL_YN char(1),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (FUND_NO)
) WITHOUT OIDS;


-- 펀드투자자(조합원)
CREATE TABLE TB_FUND_INVSTR
(
	SN numeric(10) NOT NULL,
	FUND_NO varchar(20) NOT NULL,
	BZENTY_NO varchar(20),
	INVT_BZENTY_NM varchar(100),
	BRNO char(10),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 펀드지원정보(IR지원)
CREATE TABLE TB_FUND_SPRT
(
	FUND_NO varchar(20) NOT NULL,
	BZENTY_NO varchar(20) NOT NULL,
	IR_RLS_YN char(1),
	SPRT_STTS_CD varchar(3),
	SPRT_YMD varchar(8),
	RVW_YMD varchar(8),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (FUND_NO, BZENTY_NO)
) WITHOUT OIDS;


-- 매칭설정관리
CREATE TABLE TB_MTCHG_STNG
(
	USER_NO varchar(20) NOT NULL,
	STNG_SE_CD varchar(3) NOT NULL,
	STNG_DTL_CD varchar(10) NOT NULL,
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (USER_NO, STNG_SE_CD, STNG_DTL_CD)
) WITHOUT OIDS;


-- 미팅신청
CREATE TABLE TB_MTG_APLY
(
	SN numeric(10) NOT NULL,
	APLCNT_NO varchar(20),
	TRGT_BZENTY_NO varchar(20),
	APLY_CN varchar(4000),
	APLY_YMD varchar(8),
	RSPNS_CN varchar(4000),
	RSPNS_YMD varchar(8),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 기업IR의견검토
CREATE TABLE TB_OPINION_IR
(
	EVNT_NO varchar(20) NOT NULL,
	BZENTY_NO varchar(20) NOT NULL,
	EVNT_PARTCPTN_NO varchar(20) NOT NULL,
	BIZ_CN varchar(4000),
	PRDCT_CN varchar(2000),
	CO_CN varchar(2000),
	GNRLZ_OPNN varchar(2000),
	INVT_ITRST_DGREE_CD varchar(3),
	FLLW_MTG_INTEN_YN char(1),
	PRGRS_STTS_CD varchar(10),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (EVNT_NO, BZENTY_NO, EVNT_PARTCPTN_NO)
) WITHOUT OIDS;


-- 지원사업이력
CREATE TABLE TB_SPRT_BIZ
(
	SN numeric(10) NOT NULL,
	CRDNS_BZENTY_NO varchar(20) NOT NULL,
	CRDNS_BZENTY_NM varchar(100),
	BZENTY_NO varchar(20) NOT NULL,
	BZENTY_NM varchar(100),
	BIZ_YR char(4),
	BIZ_NM varchar(100),
	ARTCL_NM1 varchar(100),
	ARTCL_CN1 varchar(300),
	ARTCL_NM2 varchar(100),
	ARTCL_CN2 varchar(300),
	ARTCL_NM3 varchar(100),
	ARTCL_CN3 varchar(300),
	ARTCL_NM4 varchar(100),
	ARTCL_CN4 varchar(300),
	ARTCL_NM5 varchar(100),
	ARTCL_CN5 varchar(300),
	RLS_YN char(1),
	DEL_YN char(1),
	ULD_NO numeric(10),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 지원사업업로드이력
CREATE TABLE TB_SPRT_ULD
(
	ULD_NO numeric(10) NOT NULL,
	FILE_NM varchar(200),
	FILE_PATH varchar(200),
	STRG_FILE_NM varchar(200),
	RMRK1 varchar(300),
	RMRK2 varchar(300),
	RMRK3 varchar(300),
	RMRK4 varchar(300),
	RMRK5 varchar(300),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	PRIMARY KEY (ULD_NO)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE TB_OPINION_IR
	ADD FOREIGN KEY (EVNT_PARTCPTN_NO)
	REFERENCES TB_EVENT_ENT (EVNT_PARTCPTN_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_OPINION_IR
	ADD FOREIGN KEY (EVNT_NO, BZENTY_NO)
	REFERENCES TB_EVENT_INVT (EVNT_NO, BZENTY_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_EVENT_ENT
	ADD FOREIGN KEY (EVNT_NO)
	REFERENCES TB_EVENT_MNG (EVNT_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_EVENT_INVT
	ADD FOREIGN KEY (EVNT_NO)
	REFERENCES TB_EVENT_MNG (EVNT_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_FUND_INVSTR
	ADD FOREIGN KEY (FUND_NO)
	REFERENCES TB_FUND_INFO (FUND_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_FUND_SPRT
	ADD FOREIGN KEY (FUND_NO)
	REFERENCES TB_FUND_INFO (FUND_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_SPRT_BIZ
	ADD FOREIGN KEY (ULD_NO)
	REFERENCES TB_SPRT_ULD (ULD_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON TABLE TB_BKMK_INFO IS '북마크정보';
COMMENT ON COLUMN TB_BKMK_INFO.SN IS '일련번호';
COMMENT ON COLUMN TB_BKMK_INFO.BZENTY_NO IS '업체번호';
COMMENT ON COLUMN TB_BKMK_INFO.TRGT_BZENTY_NO IS '대상업체번호';
COMMENT ON COLUMN TB_BKMK_INFO.DOC_NO IS '문서번호';
COMMENT ON COLUMN TB_BKMK_INFO.BKMK_SE_CD IS '북마크구분코드';
COMMENT ON COLUMN TB_BKMK_INFO.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_BKMK_INFO.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_BKMK_INFO.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_BKMK_INFO.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_EVENT_ENT IS '행사참여경영체';
COMMENT ON COLUMN TB_EVENT_ENT.EVNT_PARTCPTN_NO IS '행사참여번호';
COMMENT ON COLUMN TB_EVENT_ENT.EVNT_NO IS '행사번호';
COMMENT ON COLUMN TB_EVENT_ENT.BZENTY_NO IS '업체번호';
COMMENT ON COLUMN TB_EVENT_ENT.BRNO IS '사업자등록번호';
COMMENT ON COLUMN TB_EVENT_ENT.BZENTY_NM IS '업체명';
COMMENT ON COLUMN TB_EVENT_ENT.RPRSV_NM IS '대표자명';
COMMENT ON COLUMN TB_EVENT_ENT.TELNO IS '전화번호';
COMMENT ON COLUMN TB_EVENT_ENT.EML_ADDR IS '이메일주소';
COMMENT ON COLUMN TB_EVENT_ENT.MAIN_BIZ_CN IS '주요사업내용';
COMMENT ON COLUMN TB_EVENT_ENT.INQ_CNT IS '조회수';
COMMENT ON COLUMN TB_EVENT_ENT.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_EVENT_ENT.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_EVENT_ENT.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_EVENT_ENT.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_EVENT_INVT IS '행사참여투자자';
COMMENT ON COLUMN TB_EVENT_INVT.EVNT_NO IS '행사번호';
COMMENT ON COLUMN TB_EVENT_INVT.BZENTY_NO IS '업체번호';
COMMENT ON COLUMN TB_EVENT_INVT.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_EVENT_INVT.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_EVENT_INVT.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_EVENT_INVT.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_EVENT_MNG IS '행사관리(투자설명회)';
COMMENT ON COLUMN TB_EVENT_MNG.EVNT_NO IS '행사번호';
COMMENT ON COLUMN TB_EVENT_MNG.EVNT_NM IS '행사명';
COMMENT ON COLUMN TB_EVENT_MNG.EVNT_CN IS '행사내용';
COMMENT ON COLUMN TB_EVENT_MNG.EVNT_BGNG_YMD IS '행사시작일자';
COMMENT ON COLUMN TB_EVENT_MNG.EVNT_END_YMD IS '행사종료일자';
COMMENT ON COLUMN TB_EVENT_MNG.EVNT_YR IS '행사연도';
COMMENT ON COLUMN TB_EVENT_MNG.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_EVENT_MNG.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TB_EVENT_MNG.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_EVENT_MNG.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_EVENT_MNG.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_EVENT_MNG.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_FUND_INFO IS '펀드정보(모태펀드)';
COMMENT ON COLUMN TB_FUND_INFO.FUND_NO IS '펀드번호';
COMMENT ON COLUMN TB_FUND_INFO.FUND_NM IS '펀드명';
COMMENT ON COLUMN TB_FUND_INFO.FUND_CN IS '펀드내용';
COMMENT ON COLUMN TB_FUND_INFO.INVT_FLD_CD IS '투자분야코드';
COMMENT ON COLUMN TB_FUND_INFO.FUND_OPER_SCALE IS '펀드운영규모';
COMMENT ON COLUMN TB_FUND_INFO.MAKE_YR IS '조성연도';
COMMENT ON COLUMN TB_FUND_INFO.ORGZ_YMD IS '결성일자';
COMMENT ON COLUMN TB_FUND_INFO.INVT_BGNG_YMD IS '투자시작일자';
COMMENT ON COLUMN TB_FUND_INFO.INVT_END_YMD IS '투자종료일자';
COMMENT ON COLUMN TB_FUND_INFO.MXTR_STTS_CD IS '조합상태코드';
COMMENT ON COLUMN TB_FUND_INFO.MMBS1 IS '조합원1';
COMMENT ON COLUMN TB_FUND_INFO.MMBS2 IS '조합원2';
COMMENT ON COLUMN TB_FUND_INFO.MMBS3 IS '조합원3';
COMMENT ON COLUMN TB_FUND_INFO.MMBS4 IS '조합원4';
COMMENT ON COLUMN TB_FUND_INFO.MMBS5 IS '조합원5';
COMMENT ON COLUMN TB_FUND_INFO.RPRS_TELNO IS '대표전화번호';
COMMENT ON COLUMN TB_FUND_INFO.RPRS_HMPG_ADDR IS '대표홈페이지주소';
COMMENT ON COLUMN TB_FUND_INFO.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_FUND_INFO.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TB_FUND_INFO.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_FUND_INFO.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_FUND_INFO.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_FUND_INFO.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_FUND_INVSTR IS '펀드투자자(조합원)';
COMMENT ON COLUMN TB_FUND_INVSTR.SN IS '일련번호';
COMMENT ON COLUMN TB_FUND_INVSTR.FUND_NO IS '펀드번호';
COMMENT ON COLUMN TB_FUND_INVSTR.BZENTY_NO IS '업체번호';
COMMENT ON COLUMN TB_FUND_INVSTR.INVT_BZENTY_NM IS '투자업체명';
COMMENT ON COLUMN TB_FUND_INVSTR.BRNO IS '사업자등록번호';
COMMENT ON COLUMN TB_FUND_INVSTR.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_FUND_INVSTR.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_FUND_INVSTR.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_FUND_INVSTR.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_FUND_SPRT IS '펀드지원정보(IR지원)';
COMMENT ON COLUMN TB_FUND_SPRT.FUND_NO IS '펀드번호';
COMMENT ON COLUMN TB_FUND_SPRT.BZENTY_NO IS '업체번호';
COMMENT ON COLUMN TB_FUND_SPRT.IR_RLS_YN IS 'IR공개여부';
COMMENT ON COLUMN TB_FUND_SPRT.SPRT_STTS_CD IS '지원상태코드';
COMMENT ON COLUMN TB_FUND_SPRT.SPRT_YMD IS '지원일자';
COMMENT ON COLUMN TB_FUND_SPRT.RVW_YMD IS '검토일자';
COMMENT ON COLUMN TB_FUND_SPRT.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_FUND_SPRT.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_FUND_SPRT.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_FUND_SPRT.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_MTCHG_STNG IS '매칭설정관리';
COMMENT ON COLUMN TB_MTCHG_STNG.USER_NO IS '사용자번호';
COMMENT ON COLUMN TB_MTCHG_STNG.STNG_SE_CD IS '설정구분코드';
COMMENT ON COLUMN TB_MTCHG_STNG.STNG_DTL_CD IS '설정세부코드';
COMMENT ON COLUMN TB_MTCHG_STNG.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_MTCHG_STNG.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_MTCHG_STNG.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_MTCHG_STNG.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_MTG_APLY IS '미팅신청';
COMMENT ON COLUMN TB_MTG_APLY.SN IS '일련번호';
COMMENT ON COLUMN TB_MTG_APLY.APLCNT_NO IS '신청자번호';
COMMENT ON COLUMN TB_MTG_APLY.TRGT_BZENTY_NO IS '대상업체번호';
COMMENT ON COLUMN TB_MTG_APLY.APLY_CN IS '신청내용';
COMMENT ON COLUMN TB_MTG_APLY.APLY_YMD IS '신청일자';
COMMENT ON COLUMN TB_MTG_APLY.RSPNS_CN IS '응답내용';
COMMENT ON COLUMN TB_MTG_APLY.RSPNS_YMD IS '응답일자';
COMMENT ON COLUMN TB_MTG_APLY.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_MTG_APLY.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_MTG_APLY.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_MTG_APLY.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_OPINION_IR IS '기업IR의견검토';
COMMENT ON COLUMN TB_OPINION_IR.EVNT_NO IS '행사번호';
COMMENT ON COLUMN TB_OPINION_IR.BZENTY_NO IS '업체번호';
COMMENT ON COLUMN TB_OPINION_IR.EVNT_PARTCPTN_NO IS '행사참여번호';
COMMENT ON COLUMN TB_OPINION_IR.BIZ_CN IS '사업내용';
COMMENT ON COLUMN TB_OPINION_IR.PRDCT_CN IS '제품내용';
COMMENT ON COLUMN TB_OPINION_IR.CO_CN IS '회사내용';
COMMENT ON COLUMN TB_OPINION_IR.GNRLZ_OPNN IS '종합의견';
COMMENT ON COLUMN TB_OPINION_IR.INVT_ITRST_DGREE_CD IS '투자관심정도코드';
COMMENT ON COLUMN TB_OPINION_IR.FLLW_MTG_INTEN_YN IS '후속회의의향여부';
COMMENT ON COLUMN TB_OPINION_IR.PRGRS_STTS_CD IS '진행상태코드';
COMMENT ON COLUMN TB_OPINION_IR.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_OPINION_IR.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_OPINION_IR.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_OPINION_IR.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_SPRT_BIZ IS '지원사업이력';
COMMENT ON COLUMN TB_SPRT_BIZ.SN IS '일련번호';
COMMENT ON COLUMN TB_SPRT_BIZ.CRDNS_BZENTY_NO IS '유관기관업체번호';
COMMENT ON COLUMN TB_SPRT_BIZ.CRDNS_BZENTY_NM IS '유관기관업체명';
COMMENT ON COLUMN TB_SPRT_BIZ.BZENTY_NO IS '업체번호';
COMMENT ON COLUMN TB_SPRT_BIZ.BZENTY_NM IS '업체명';
COMMENT ON COLUMN TB_SPRT_BIZ.BIZ_YR IS '사업연도';
COMMENT ON COLUMN TB_SPRT_BIZ.BIZ_NM IS '사업명';
COMMENT ON COLUMN TB_SPRT_BIZ.ARTCL_NM1 IS '항목명1';
COMMENT ON COLUMN TB_SPRT_BIZ.ARTCL_CN1 IS '항목내용1';
COMMENT ON COLUMN TB_SPRT_BIZ.ARTCL_NM2 IS '항목명2';
COMMENT ON COLUMN TB_SPRT_BIZ.ARTCL_CN2 IS '항목내용2';
COMMENT ON COLUMN TB_SPRT_BIZ.ARTCL_NM3 IS '항목명3';
COMMENT ON COLUMN TB_SPRT_BIZ.ARTCL_CN3 IS '항목내용3';
COMMENT ON COLUMN TB_SPRT_BIZ.ARTCL_NM4 IS '항목명4';
COMMENT ON COLUMN TB_SPRT_BIZ.ARTCL_CN4 IS '항목내용4';
COMMENT ON COLUMN TB_SPRT_BIZ.ARTCL_NM5 IS '항목명5';
COMMENT ON COLUMN TB_SPRT_BIZ.ARTCL_CN5 IS '항목내용5';
COMMENT ON COLUMN TB_SPRT_BIZ.RLS_YN IS '공개여부';
COMMENT ON COLUMN TB_SPRT_BIZ.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TB_SPRT_BIZ.ULD_NO IS '업로드번호';
COMMENT ON COLUMN TB_SPRT_BIZ.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_SPRT_BIZ.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_SPRT_BIZ.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_SPRT_BIZ.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_SPRT_ULD IS '지원사업업로드이력';
COMMENT ON COLUMN TB_SPRT_ULD.ULD_NO IS '업로드번호';
COMMENT ON COLUMN TB_SPRT_ULD.FILE_NM IS '파일명';
COMMENT ON COLUMN TB_SPRT_ULD.FILE_PATH IS '파일경로';
COMMENT ON COLUMN TB_SPRT_ULD.STRG_FILE_NM IS '저장파일명';
COMMENT ON COLUMN TB_SPRT_ULD.RMRK1 IS '비고1';
COMMENT ON COLUMN TB_SPRT_ULD.RMRK2 IS '비고2';
COMMENT ON COLUMN TB_SPRT_ULD.RMRK3 IS '비고3';
COMMENT ON COLUMN TB_SPRT_ULD.RMRK4 IS '비고4';
COMMENT ON COLUMN TB_SPRT_ULD.RMRK5 IS '비고5';
COMMENT ON COLUMN TB_SPRT_ULD.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_SPRT_ULD.REG_YMD IS '등록일자';


