
/* Drop Tables */

DROP TABLE IF EXISTS TB_BIZ_FILE;
DROP TABLE IF EXISTS TB_BIZ_PBANC;
DROP TABLE IF EXISTS TB_DSCSN_APLY;
DROP TABLE IF EXISTS TB_DSCSN_DIARY;
DROP TABLE IF EXISTS TB_INVTSPRT_SLS;
DROP TABLE IF EXISTS TB_INVT_MXTR;
DROP TABLE IF EXISTS TB_SPRT_BIZ_PRGRE;
DROP TABLE IF EXISTS TB_INVTSPRT_APLY;
DROP TABLE IF EXISTS TB_INVTSPRT_MNG;




/* Create Tables */

-- 업무첨부파일
CREATE TABLE TB_BIZ_FILE
(
	SN numeric(10) NOT NULL,
	TASK_SE_CD varchar(10),
	DOC_NO varchar(20),
	DTL_DOC_NO varchar(20),
	FILE_SE_CD varchar(3),
	DCMNT_CD varchar(10),
	FILE_PATH varchar(200),
	STRG_FILE_NM varchar(200),
	FILE_NM varchar(200),
	FILE_SZ numeric(14),
	PRCS_STTS_CD varchar(3),
	PRCS_CN varchar(2000),
	DEL_YN char(1),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 사업공고관리
CREATE TABLE TB_BIZ_PBANC
(
	BIZ_PBANC_NO varchar(20) NOT NULL,
	BIZ_PBANC_NM varchar(100),
	CRDNS_BZENTY_NO varchar(20),
	CRDNS_BZENTY_NM varchar(100),
	BRNO char(10),
	TKCG_DEPT_NM varchar(200),
	PIC_NM varchar(20),
	PIC_TELNO varchar(11),
	BIZ_GUIDANCE_URL varchar(500),
	RCPT_SE_CD varchar(3),
	RCPT_BGNG_DT varchar(12),
	RCPT_END_DT varchar(12),
	SPRT_FLD_CD varchar(3),
	BIZ_FLD varchar(200),
	BIZ_TRGT varchar(200),
	BIZ_TRGT_AGE varchar(200),
	BIZ_TRGT_FNTN_PD varchar(200),
	RCPT_MTHD_CD varchar(3),
	RCPT_MTHD_CN varchar(2000),
	APLY_QLFC_CN varchar(2000),
	APLY_EXCL_TRGT_CN varchar(2000),
	SBMSN_DCMNT_CN varchar(2000),
	SPRT_CN varchar(2000),
	PBANC_STTS_CD varchar(3),
	DEL_YN char(1),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (BIZ_PBANC_NO)
) WITHOUT OIDS;


-- 상담신청
CREATE TABLE TB_DSCSN_APLY
(
	DSCSN_APLY_NO varchar(20) NOT NULL,
	APLY_BZENTY_NO varchar(20),
	DSCSN_APLY_YMD varchar(8),
	PIC_NM varchar(20),
	PIC_DEPT_NM varchar(200),
	PIC_TELNO varchar(11),
	PIC_EML_ADDR varchar(100),
	DSCSN_CN text,
	DSCSN_YMD varchar(8),
	PRGRS_STTS_CD varchar(10),
	PRCS_RSLT_CN varchar(2000),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (DSCSN_APLY_NO)
) WITHOUT OIDS;


-- 상담일지
CREATE TABLE TB_DSCSN_DIARY
(
	SN numeric(10) NOT NULL,
	DSCSN_CNTR_CD varchar(10),
	DSCSN_YMD varchar(8),
	DSCSN_MTHD_CD varchar(10),
	CNSLR_NM varchar(20),
	BZENTY_NM varchar(100),
	BRNO char(10),
	RPRSV_NM varchar(20),
	BRDT char(8),
	SEXDSTN char(1),
	PIC_NM varchar(20),
	PIC_DEPT_NM varchar(200),
	PIC_TELNO varchar(11),
	PIC_EML_ADDR varchar(100),
	FNDN_YMD varchar(8),
	EMP_CNT numeric(10),
	BZENTY_TYPE_CD varchar(3),
	BIZ_FLD varchar(200),
	INVT_FLD_NM varchar(100),
	TPBIZ_SE_NM varchar(100),
	INDUST_SE_NM varchar(100),
	SLS_AMT numeric(15),
	HMPG_ADDR varchar(500),
	LCTN_ADDR1 varchar(200),
	LCTN_ADDR2 varchar(200),
	BIZ_CN varchar(4000),
	DSCSN_CN text,
	PRGRS_STTS_CD varchar(10),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 투자지원신청
CREATE TABLE TB_INVTSPRT_APLY
(
	SPRT_APLY_NO varchar(20) NOT NULL,
	SPRT_APLY_SE_CD varchar(10) NOT NULL,
	PRGRM_NO varchar(10),
	APLY_BZENTY_NO varchar(20),
	APLY_USER_NO varchar(20),
	PRVC_CLCT_AGRE_YN char(1),
	UNITY_MNG_SYS_AGRE_YN char(1),
	BZENTY_NM varchar(100),
	BRNO char(10),
	FNDN_YMD varchar(8),
	RPRSV_NM varchar(20),
	EMP_CNT numeric(10),
	CRNO char(13),
	BRDT char(8),
	SEXDSTN char(1),
	LCTN_ADDR varchar(200),
	LCTN_DADDR varchar(200),
	RPRS_TELNO varchar(11),
	FXNO varchar(20),
	BZENTY_TYPE_CD varchar(3),
	BIZ_FLD varchar(200),
	HMPG_ADDR varchar(500),
	INVT_HOPE_AMT numeric(15),
	MAIN_BIZ_CN varchar(4000),
	CORE_ITM_CN varchar(4000),
	BIZ_CN varchar(4000),
	PIC_NM varchar(20),
	PIC_DEPT_NM varchar(200),
	PIC_TELNO varchar(11),
	PIC_EML_ADDR varchar(100),
	FUND_LINK_URL varchar(500),
	RCPT_YMD varchar(8),
	PRCS_YMD varchar(8),
	RMRK varchar(1000),
	PRGRS_STTS_CD varchar(10),
	PRCS_RSLT_CN varchar(2000),
	DEL_YN char(1),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (SPRT_APLY_NO)
) WITHOUT OIDS;


-- 투자지원프로그램관리
CREATE TABLE TB_INVTSPRT_MNG
(
	PRGRM_NO varchar(10) NOT NULL,
	SPRT_APLY_SE_CD varchar(10) NOT NULL,
	PRGRM_CLSF_CD varchar(10) NOT NULL,
	PRGRM_NM varchar(100),
	SPRT_BGNG_YMD varchar(8),
	SPRT_END_YMD varchar(8),
	USE_YN char(1),
	DEL_YN char(1),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (PRGRM_NO)
) WITHOUT OIDS;


-- 매출정보
CREATE TABLE TB_INVTSPRT_SLS
(
	SN numeric(10) NOT NULL,
	SPRT_APLY_NO varchar(20) NOT NULL,
	FNNR_YMD varchar(8),
	FNNR_AMT numeric(15),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 투자조합정보
CREATE TABLE TB_INVT_MXTR
(
	SN numeric(10) NOT NULL,
	SPRT_APLY_NO varchar(20) NOT NULL,
	INVT_MXTR_NM varchar(100),
	INVT_YMD varchar(8),
	INVSTR_NM varchar(100),
	INVT_AMT numeric(15),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 지원사업진행현황
CREATE TABLE TB_SPRT_BIZ_PRGRE
(
	SN numeric(10) NOT NULL,
	SPRT_APLY_NO varchar(20) NOT NULL,
	PRGRM_SE_CD varchar(10),
	DSCSN_CNTR_CD varchar(10),
	PRCS_CYCL numeric(3),
	FTF_YN char(1),
	PRGRS_CN varchar(300),
	PIC_NM varchar(20),
	PIC_TELNO varchar(11),
	EVNT_NO varchar(20),
	PRGRS_STTS_CD varchar(10),
	PRGRS_DETAIL_STTS_CD varchar(10),
	PRCS_YMD varchar(8),
	RGTR_NO varchar(20),
	REG_YMD timestamp,
	MDFR_NO varchar(20),
	MDFCN_YMD timestamp,
	PRIMARY KEY (SN)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE TB_INVTSPRT_SLS
	ADD FOREIGN KEY (SPRT_APLY_NO)
	REFERENCES TB_INVTSPRT_APLY (SPRT_APLY_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_INVT_MXTR
	ADD FOREIGN KEY (SPRT_APLY_NO)
	REFERENCES TB_INVTSPRT_APLY (SPRT_APLY_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_SPRT_BIZ_PRGRE
	ADD FOREIGN KEY (SPRT_APLY_NO)
	REFERENCES TB_INVTSPRT_APLY (SPRT_APLY_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_INVTSPRT_APLY
	ADD FOREIGN KEY (PRGRM_NO)
	REFERENCES TB_INVTSPRT_MNG (PRGRM_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON TABLE TB_BIZ_FILE IS '업무첨부파일';
COMMENT ON COLUMN TB_BIZ_FILE.SN IS '일련번호';
COMMENT ON COLUMN TB_BIZ_FILE.TASK_SE_CD IS '업무구분코드';
COMMENT ON COLUMN TB_BIZ_FILE.DOC_NO IS '문서번호';
COMMENT ON COLUMN TB_BIZ_FILE.DTL_DOC_NO IS '세부문서번호';
COMMENT ON COLUMN TB_BIZ_FILE.FILE_SE_CD IS '파일구분코드';
COMMENT ON COLUMN TB_BIZ_FILE.DCMNT_CD IS '서류코드';
COMMENT ON COLUMN TB_BIZ_FILE.FILE_PATH IS '파일경로';
COMMENT ON COLUMN TB_BIZ_FILE.STRG_FILE_NM IS '저장파일명';
COMMENT ON COLUMN TB_BIZ_FILE.FILE_NM IS '파일명';
COMMENT ON COLUMN TB_BIZ_FILE.FILE_SZ IS '파일크기';
COMMENT ON COLUMN TB_BIZ_FILE.PRCS_STTS_CD IS '처리상태코드';
COMMENT ON COLUMN TB_BIZ_FILE.PRCS_CN IS '처리내용';
COMMENT ON COLUMN TB_BIZ_FILE.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TB_BIZ_FILE.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_BIZ_FILE.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_BIZ_FILE.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_BIZ_FILE.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_BIZ_PBANC IS '사업공고관리';
COMMENT ON COLUMN TB_BIZ_PBANC.BIZ_PBANC_NO IS '사업공고번호';
COMMENT ON COLUMN TB_BIZ_PBANC.BIZ_PBANC_NM IS '사업공고명';
COMMENT ON COLUMN TB_BIZ_PBANC.CRDNS_BZENTY_NO IS '유관기관업체번호';
COMMENT ON COLUMN TB_BIZ_PBANC.CRDNS_BZENTY_NM IS '유관기관업체명';
COMMENT ON COLUMN TB_BIZ_PBANC.BRNO IS '사업자등록번호';
COMMENT ON COLUMN TB_BIZ_PBANC.TKCG_DEPT_NM IS '담당부서명';
COMMENT ON COLUMN TB_BIZ_PBANC.PIC_NM IS '담당자명';
COMMENT ON COLUMN TB_BIZ_PBANC.PIC_TELNO IS '담당자전화번호';
COMMENT ON COLUMN TB_BIZ_PBANC.BIZ_GUIDANCE_URL IS '사업안내URL';
COMMENT ON COLUMN TB_BIZ_PBANC.RCPT_SE_CD IS '접수구분코드';
COMMENT ON COLUMN TB_BIZ_PBANC.RCPT_BGNG_DT IS '접수시작일시';
COMMENT ON COLUMN TB_BIZ_PBANC.RCPT_END_DT IS '접수종료일시';
COMMENT ON COLUMN TB_BIZ_PBANC.SPRT_FLD_CD IS '지원분야코드';
COMMENT ON COLUMN TB_BIZ_PBANC.BIZ_FLD IS '사업분야';
COMMENT ON COLUMN TB_BIZ_PBANC.BIZ_TRGT IS '사업대상';
COMMENT ON COLUMN TB_BIZ_PBANC.BIZ_TRGT_AGE IS '사업대상연령';
COMMENT ON COLUMN TB_BIZ_PBANC.BIZ_TRGT_FNTN_PD IS '사업대상창업기간';
COMMENT ON COLUMN TB_BIZ_PBANC.RCPT_MTHD_CD IS '접수방법코드';
COMMENT ON COLUMN TB_BIZ_PBANC.RCPT_MTHD_CN IS '접수방법내용';
COMMENT ON COLUMN TB_BIZ_PBANC.APLY_QLFC_CN IS '신청자격내용';
COMMENT ON COLUMN TB_BIZ_PBANC.APLY_EXCL_TRGT_CN IS '신청제외대상내용';
COMMENT ON COLUMN TB_BIZ_PBANC.SBMSN_DCMNT_CN IS '제출서류내용';
COMMENT ON COLUMN TB_BIZ_PBANC.SPRT_CN IS '지원내용';
COMMENT ON COLUMN TB_BIZ_PBANC.PBANC_STTS_CD IS '공고상태코드';
COMMENT ON COLUMN TB_BIZ_PBANC.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TB_BIZ_PBANC.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_BIZ_PBANC.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_BIZ_PBANC.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_BIZ_PBANC.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_DSCSN_APLY IS '상담신청';
COMMENT ON COLUMN TB_DSCSN_APLY.DSCSN_APLY_NO IS '상담신청번호';
COMMENT ON COLUMN TB_DSCSN_APLY.APLY_BZENTY_NO IS '신청업체번호';
COMMENT ON COLUMN TB_DSCSN_APLY.DSCSN_APLY_YMD IS '상담신청일자';
COMMENT ON COLUMN TB_DSCSN_APLY.PIC_NM IS '담당자명';
COMMENT ON COLUMN TB_DSCSN_APLY.PIC_DEPT_NM IS '담당자부서명';
COMMENT ON COLUMN TB_DSCSN_APLY.PIC_TELNO IS '담당자전화번호';
COMMENT ON COLUMN TB_DSCSN_APLY.PIC_EML_ADDR IS '담당자이메일주소';
COMMENT ON COLUMN TB_DSCSN_APLY.DSCSN_CN IS '상담내용';
COMMENT ON COLUMN TB_DSCSN_APLY.DSCSN_YMD IS '상담일자';
COMMENT ON COLUMN TB_DSCSN_APLY.PRGRS_STTS_CD IS '진행상태코드';
COMMENT ON COLUMN TB_DSCSN_APLY.PRCS_RSLT_CN IS '처리결과내용';
COMMENT ON COLUMN TB_DSCSN_APLY.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_DSCSN_APLY.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_DSCSN_APLY.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_DSCSN_APLY.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_DSCSN_DIARY IS '상담일지';
COMMENT ON COLUMN TB_DSCSN_DIARY.SN IS '일련번호';
COMMENT ON COLUMN TB_DSCSN_DIARY.DSCSN_CNTR_CD IS '상담센터코드';
COMMENT ON COLUMN TB_DSCSN_DIARY.DSCSN_YMD IS '상담일자';
COMMENT ON COLUMN TB_DSCSN_DIARY.DSCSN_MTHD_CD IS '상담방법코드';
COMMENT ON COLUMN TB_DSCSN_DIARY.CNSLR_NM IS '상담원명';
COMMENT ON COLUMN TB_DSCSN_DIARY.BZENTY_NM IS '업체명';
COMMENT ON COLUMN TB_DSCSN_DIARY.BRNO IS '사업자등록번호';
COMMENT ON COLUMN TB_DSCSN_DIARY.RPRSV_NM IS '대표자명';
COMMENT ON COLUMN TB_DSCSN_DIARY.BRDT IS '생년월일';
COMMENT ON COLUMN TB_DSCSN_DIARY.SEXDSTN IS '성별';
COMMENT ON COLUMN TB_DSCSN_DIARY.PIC_NM IS '담당자명';
COMMENT ON COLUMN TB_DSCSN_DIARY.PIC_DEPT_NM IS '담당자부서명';
COMMENT ON COLUMN TB_DSCSN_DIARY.PIC_TELNO IS '담당자전화번호';
COMMENT ON COLUMN TB_DSCSN_DIARY.PIC_EML_ADDR IS '담당자이메일주소';
COMMENT ON COLUMN TB_DSCSN_DIARY.FNDN_YMD IS '설립일자';
COMMENT ON COLUMN TB_DSCSN_DIARY.EMP_CNT IS '직원수';
COMMENT ON COLUMN TB_DSCSN_DIARY.BZENTY_TYPE_CD IS '업체유형코드';
COMMENT ON COLUMN TB_DSCSN_DIARY.BIZ_FLD IS '사업분야';
COMMENT ON COLUMN TB_DSCSN_DIARY.INVT_FLD_NM IS '투자분야명';
COMMENT ON COLUMN TB_DSCSN_DIARY.TPBIZ_SE_NM IS '업종구분명';
COMMENT ON COLUMN TB_DSCSN_DIARY.INDUST_SE_NM IS '산업구분명';
COMMENT ON COLUMN TB_DSCSN_DIARY.SLS_AMT IS '매출금액';
COMMENT ON COLUMN TB_DSCSN_DIARY.HMPG_ADDR IS '홈페이지주소';
COMMENT ON COLUMN TB_DSCSN_DIARY.LCTN_ADDR1 IS '소재지주소1';
COMMENT ON COLUMN TB_DSCSN_DIARY.LCTN_ADDR2 IS '소재지주소2';
COMMENT ON COLUMN TB_DSCSN_DIARY.BIZ_CN IS '사업내용';
COMMENT ON COLUMN TB_DSCSN_DIARY.DSCSN_CN IS '상담내용';
COMMENT ON COLUMN TB_DSCSN_DIARY.PRGRS_STTS_CD IS '진행상태코드';
COMMENT ON COLUMN TB_DSCSN_DIARY.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_DSCSN_DIARY.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_DSCSN_DIARY.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_DSCSN_DIARY.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_INVTSPRT_APLY IS '투자지원신청';
COMMENT ON COLUMN TB_INVTSPRT_APLY.SPRT_APLY_NO IS '지원신청번호';
COMMENT ON COLUMN TB_INVTSPRT_APLY.SPRT_APLY_SE_CD IS '지원신청구분코드';
COMMENT ON COLUMN TB_INVTSPRT_APLY.PRGRM_NO IS '프로그램번호';
COMMENT ON COLUMN TB_INVTSPRT_APLY.APLY_BZENTY_NO IS '신청업체번호';
COMMENT ON COLUMN TB_INVTSPRT_APLY.APLY_USER_NO IS '신청사용자번호';
COMMENT ON COLUMN TB_INVTSPRT_APLY.PRVC_CLCT_AGRE_YN IS '개인정보수집동의여부';
COMMENT ON COLUMN TB_INVTSPRT_APLY.UNITY_MNG_SYS_AGRE_YN IS '통합관리시스템동의여부';
COMMENT ON COLUMN TB_INVTSPRT_APLY.BZENTY_NM IS '업체명';
COMMENT ON COLUMN TB_INVTSPRT_APLY.BRNO IS '사업자등록번호';
COMMENT ON COLUMN TB_INVTSPRT_APLY.FNDN_YMD IS '설립일자';
COMMENT ON COLUMN TB_INVTSPRT_APLY.RPRSV_NM IS '대표자명';
COMMENT ON COLUMN TB_INVTSPRT_APLY.EMP_CNT IS '직원수';
COMMENT ON COLUMN TB_INVTSPRT_APLY.CRNO IS '법인등록번호';
COMMENT ON COLUMN TB_INVTSPRT_APLY.BRDT IS '생년월일';
COMMENT ON COLUMN TB_INVTSPRT_APLY.SEXDSTN IS '성별';
COMMENT ON COLUMN TB_INVTSPRT_APLY.LCTN_ADDR IS '소재지주소';
COMMENT ON COLUMN TB_INVTSPRT_APLY.LCTN_DADDR IS '소재지상세주소';
COMMENT ON COLUMN TB_INVTSPRT_APLY.RPRS_TELNO IS '대표전화번호';
COMMENT ON COLUMN TB_INVTSPRT_APLY.FXNO IS '팩스번호';
COMMENT ON COLUMN TB_INVTSPRT_APLY.BZENTY_TYPE_CD IS '업체유형코드';
COMMENT ON COLUMN TB_INVTSPRT_APLY.BIZ_FLD IS '사업분야';
COMMENT ON COLUMN TB_INVTSPRT_APLY.HMPG_ADDR IS '홈페이지주소';
COMMENT ON COLUMN TB_INVTSPRT_APLY.INVT_HOPE_AMT IS '투자희망금액';
COMMENT ON COLUMN TB_INVTSPRT_APLY.MAIN_BIZ_CN IS '주요사업내용';
COMMENT ON COLUMN TB_INVTSPRT_APLY.CORE_ITM_CN IS '핵심아이템내용';
COMMENT ON COLUMN TB_INVTSPRT_APLY.BIZ_CN IS '사업내용';
COMMENT ON COLUMN TB_INVTSPRT_APLY.PIC_NM IS '담당자명';
COMMENT ON COLUMN TB_INVTSPRT_APLY.PIC_DEPT_NM IS '담당자부서명';
COMMENT ON COLUMN TB_INVTSPRT_APLY.PIC_TELNO IS '담당자전화번호';
COMMENT ON COLUMN TB_INVTSPRT_APLY.PIC_EML_ADDR IS '담당자이메일주소';
COMMENT ON COLUMN TB_INVTSPRT_APLY.FUND_LINK_URL IS '펀드링크URL';
COMMENT ON COLUMN TB_INVTSPRT_APLY.RCPT_YMD IS '접수일자';
COMMENT ON COLUMN TB_INVTSPRT_APLY.PRCS_YMD IS '처리일자';
COMMENT ON COLUMN TB_INVTSPRT_APLY.RMRK IS '비고';
COMMENT ON COLUMN TB_INVTSPRT_APLY.PRGRS_STTS_CD IS '진행상태코드';
COMMENT ON COLUMN TB_INVTSPRT_APLY.PRCS_RSLT_CN IS '처리결과내용';
COMMENT ON COLUMN TB_INVTSPRT_APLY.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TB_INVTSPRT_APLY.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_INVTSPRT_APLY.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_INVTSPRT_APLY.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_INVTSPRT_APLY.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_INVTSPRT_MNG IS '투자지원프로그램관리';
COMMENT ON COLUMN TB_INVTSPRT_MNG.PRGRM_NO IS '프로그램번호';
COMMENT ON COLUMN TB_INVTSPRT_MNG.SPRT_APLY_SE_CD IS '지원신청구분코드';
COMMENT ON COLUMN TB_INVTSPRT_MNG.PRGRM_CLSF_CD IS '프로그램분류코드';
COMMENT ON COLUMN TB_INVTSPRT_MNG.PRGRM_NM IS '프로그램명';
COMMENT ON COLUMN TB_INVTSPRT_MNG.SPRT_BGNG_YMD IS '지원시작일자';
COMMENT ON COLUMN TB_INVTSPRT_MNG.SPRT_END_YMD IS '지원종료일자';
COMMENT ON COLUMN TB_INVTSPRT_MNG.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_INVTSPRT_MNG.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TB_INVTSPRT_MNG.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_INVTSPRT_MNG.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_INVTSPRT_MNG.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_INVTSPRT_MNG.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_INVTSPRT_SLS IS '매출정보';
COMMENT ON COLUMN TB_INVTSPRT_SLS.SN IS '일련번호';
COMMENT ON COLUMN TB_INVTSPRT_SLS.SPRT_APLY_NO IS '지원신청번호';
COMMENT ON COLUMN TB_INVTSPRT_SLS.FNNR_YMD IS '재무일자';
COMMENT ON COLUMN TB_INVTSPRT_SLS.FNNR_AMT IS '재무금액';
COMMENT ON COLUMN TB_INVTSPRT_SLS.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_INVTSPRT_SLS.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_INVTSPRT_SLS.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_INVTSPRT_SLS.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_INVT_MXTR IS '투자조합정보';
COMMENT ON COLUMN TB_INVT_MXTR.SN IS '일련번호';
COMMENT ON COLUMN TB_INVT_MXTR.SPRT_APLY_NO IS '지원신청번호';
COMMENT ON COLUMN TB_INVT_MXTR.INVT_MXTR_NM IS '투자조합명';
COMMENT ON COLUMN TB_INVT_MXTR.INVT_YMD IS '투자일자';
COMMENT ON COLUMN TB_INVT_MXTR.INVSTR_NM IS '투자자명';
COMMENT ON COLUMN TB_INVT_MXTR.INVT_AMT IS '투자금액';
COMMENT ON COLUMN TB_INVT_MXTR.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_INVT_MXTR.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_INVT_MXTR.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_INVT_MXTR.MDFCN_YMD IS '수정일자';
COMMENT ON TABLE TB_SPRT_BIZ_PRGRE IS '지원사업진행현황';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.SN IS '일련번호';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.SPRT_APLY_NO IS '지원신청번호';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.PRGRM_SE_CD IS '프로그램구분코드';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.DSCSN_CNTR_CD IS '상담센터코드';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.PRCS_CYCL IS '처리차수';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.FTF_YN IS '대면여부';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.PRGRS_CN IS '진행내용';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.PIC_NM IS '담당자명';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.PIC_TELNO IS '담당자전화번호';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.EVNT_NO IS '행사번호';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.PRGRS_STTS_CD IS '진행상태코드';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.PRGRS_DETAIL_STTS_CD IS '진행세부상태코드';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.PRCS_YMD IS '처리일자';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN TB_SPRT_BIZ_PRGRE.MDFCN_YMD IS '수정일자';



