
/* Drop Tables */

DROP TABLE IF EXISTS IF_5038;
DROP TABLE IF EXISTS IF_5039;
DROP TABLE IF EXISTS IF_5041;
DROP TABLE IF EXISTS IF_5056;
DROP TABLE IF EXISTS IF_5057;
DROP TABLE IF EXISTS IF_5058;
DROP TABLE IF EXISTS IF_5062;
DROP TABLE IF EXISTS IF_5063;
DROP TABLE IF EXISTS IF_50D1;
DROP TABLE IF EXISTS IF_50D2;
DROP TABLE IF EXISTS IF_50PA;
DROP TABLE IF EXISTS IF_50TA;
DROP TABLE IF EXISTS IF_50TB;
DROP TABLE IF EXISTS IF_50TF;
DROP TABLE IF EXISTS IF_50TG;
DROP TABLE IF EXISTS IF_50TH;
DROP TABLE IF EXISTS IF_50TI;
DROP TABLE IF EXISTS IF_50TK;
DROP TABLE IF EXISTS IF_50TL;




/* Create Tables */

-- 재무분석계정코드
CREATE TABLE IF_5038
(
	SN numeric(10) NOT NULL,
	ACC_CD_FULL varchar(10),
	FS_INFO_CD varchar(2),
	FS_BZC_CD varchar(2),
	FS_CCD_ANAL varchar(1),
	ACC_CD varchar(5),
	ACC_NM varchar(60),
	ACC_NM_ENG varchar(300),
	UNT varchar(10),
	ATHXP varchar(2000),
	ATHXP_CTT varchar(2000),
	PIC_CCD varchar(1),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 재무분석DATA
CREATE TABLE IF_5039
(
	SN numeric(10) NOT NULL,
	KEDCD varchar(10),
	STTL_BASE_YM_DD varchar(8),
	FS_INFO_CD varchar(2),
	ACCT_CCD varchar(1),
	ACC_CD_FULL varchar(10),
	VAL varchar(30),
	ITM_STL varchar(20),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 종합신용등급
CREATE TABLE IF_5041
(
	SN numeric(10) NOT NULL,
	KEDCD varchar(10),
	REG_DT varchar(8),
	EVL_DT varchar(8),
	STTL_BASE_DD varchar(8),
	GRD_CLS varchar(2),
	CR_GRD varchar(8),
	MODL_EVL_DT varchar(8),
	IVG_MTD_CLS varchar(2),
	GRD_SV_ST_DD varchar(8),
	GRD_SV_EDDT varchar(8),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 신계정_재무계정코드
CREATE TABLE IF_5056
(
	SN numeric(10) NOT NULL,
	ACC_CD_FULL varchar(10),
	FS_INFO_CD varchar(2),
	FS_BZC_CD varchar(2),
	FS_CCD varchar(1),
	ACC_CD varchar(5),
	ACC_NM varchar(60),
	ACC_NM_ENG varchar(300),
	UNT varchar(10),
	ATHXP varchar(2000),
	ATHXP_CTT varchar(2000),
	ACC_CD_LVL varchar(1),
	IVG_INP_ACC_YN varchar(1),
	SMRY_FIN_YN varchar(1),
	HELP_YN varchar(1),
	BS_SMRY_YN varchar(1),
	MUS_YN varchar(1),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 신계정_재무제표MASTER
CREATE TABLE IF_5057
(
	SN numeric(10) NOT NULL,
	KEDCD varchar(10),
	ACCT_DT varchar(8),
	FS_CCD varchar(1),
	ACCT_CCD varchar(1),
	ACCT_STDT varchar(8),
	ACCT_EDDT varchar(8),
	FS_INFO_CD varchar(2),
	FS_BZC_CD varchar(2),
	BOOK_ETRY_CCD varchar(2),
	WRT_BAS_CD varchar(2),
	TRF_YN varchar(2),
	STD_DT varchar(8),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 신계정_재무제표DATA
CREATE TABLE IF_5058
(
	SN numeric(10) NOT NULL,
	KEDCD varchar(10),
	ACCT_DT varchar(8),
	FS_CCD varchar(1),
	ACCT_CCD varchar(1),
	ACC_CD_FULL varchar(10),
	VAL varchar(13),
	RT varchar(12),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- (신회계)재무비율계정코드
CREATE TABLE IF_5062
(
	SN numeric(10) NOT NULL,
	ACC_CD_FULL varchar(10),
	FS_INFO_CD varchar(2),
	FS_BZC_CD varchar(2),
	FS_CCD_RT varchar(1),
	ACC_CD varchar(5),
	ACC_NM varchar(60),
	ACC_NM_ENG varchar(300),
	UNT varchar(10),
	ATHXP varchar(2000),
	ATHXP_CTT varchar(2000),
	QT_CRE_CCD varchar(1),
	PRD_CRE_CCD varchar(1),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- (신회계)재무비율DATA
CREATE TABLE IF_5063
(
	SN numeric(10) NOT NULL,
	KEDCD varchar(10),
	ACCT_DT varchar(8),
	ACCT_CCD varchar(1),
	ACC_CD_FULL varchar(10),
	FS_INFO_CD varchar(2),
	FS_BZC_CD varchar(2),
	FS_CCD varchar(1),
	ACC_CD varchar(5),
	VAL varchar(22),
	ERR_CD varchar(2),
	STD_DT varchar(8),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 업체개요
CREATE TABLE IF_50D1
(
	SN numeric(10) NOT NULL,
	KEDCD varchar(10) NOT NULL,
	ENP_NM varchar(100),
	ENP_NM_TRD varchar(100),
	ENP_NM_ENG varchar(200),
	ENP_TYP varchar(1),
	ENP_SZE varchar(2),
	GRDT_PLN_DT varchar(8),
	ENP_FCD varchar(2),
	ESTB_FCD varchar(2),
	ENP_SCD varchar(2),
	ENP_SCD_CHG_DT varchar(8),
	PUBI_FCD varchar(2),
	VENP_YN varchar(1),
	ENP_FORM_FR varchar(1),
	BZC_CD varchar(6),
	FS_BZC_CD varchar(2),
	GRP_CD varchar(4),
	GRP_NM varchar(50),
	CONO_PID varchar(13),
	ESTB_DT varchar(8),
	IPO_CD varchar(1),
	TRDBZ_RPT_NO varchar(10),
	LIST_DT varchar(8),
	DLIST_DT varchar(8),
	MTX_BNK_CD varchar(7),
	MTX_BNK_NM varchar(70),
	OVD_TX_BNK_CD varchar(7),
	OVD_TX_BNK_NM varchar(70),
	ACCT_EDDT varchar(4),
	HPAGE_URL varchar(50),
	EMAIL varchar(40),
	STD_DT varchar(8),
	BZNO varchar(10),
	LOC_ZIP varchar(6),
	LOC_ADDRA varchar(200),
	LOC_ADDRB varchar(200),
	TEL_NO varchar(20),
	FAX_NO varchar(20),
	LABORER_SUM varchar(13),
	PD_NM varchar(100),
	KSIC9_BZC_CD varchar(6),
	REL_KEDCD varchar(10),
	REL_ESTB_DT varchar(8),
	LOC_RDNM_ZIP varchar(6),
	LOC_RDNM_ADDRA varchar(100),
	LOC_RDNM_ADDRB varchar(200),
	LOC_RDNM_ADDRB_CONF_YN varchar(1),
	LOC_ADDRB_CONF_YN varchar(1),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 대표자정보
CREATE TABLE IF_50D2
(
	SN numeric(10) NOT NULL,
	KEDCD varchar(10),
	PCD varchar(10),
	STD_DT varchar(8),
	NAME varchar(40),
	PID varchar(13),
	REPER_CCD varchar(2),
	MRK_REPER_YN varchar(1),
	ASMP_DT varchar(8),
	RTIR_DT varchar(8),
	PO_YN varchar(1),
	TTL varchar(30),
	MNG_FCD varchar(2),
	SBZC_EG_YCN_REPER varchar(2),
	SBZC_EG_MCN_REPER varchar(2),
	SIND_EG_PRD_YY varchar(2),
	SIND_EG_PRD_MM varchar(2),
	SBZC_EVL_CD varchar(2),
	MDM_REL_CD varchar(2),
	REPER_MABL_CD varchar(2),
	CSTK_OWN varchar(13),
	PSTK_OWN varchar(13),
	SO_REG_CN varchar(13),
	RMK varchar(200),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 국민연금정보(국민연금월별정보현황)
CREATE TABLE IF_50PA
(
	SN numeric(10) NOT NULL,
	KEDCD varchar(10),
	DATA_CRE_YM varchar(6),
	JOIN_PRS_CN varchar(6),
	TMONNTTC_AM varchar(16),
	MONTY_NMFEMP varchar(6),
	MM_CFB_RTIR_PRS_CN varchar(6),
	AVG_SLRY_PE varchar(12),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 벤처인증기업
CREATE TABLE IF_50TA
(
	SN numeric(10) NOT NULL,
	BASE_DT varchar(8),
	BZNO varchar(10),
	CONO varchar(13),
	ENP_NM varchar(100),
	MAI_GDSNM1 varchar(100),
	VNTRBZ_CFMT_DV varchar(8),
	VNTR_STRT_VLDYMD varchar(8),
	VNTR_EN_VLDYMD varchar(8),
	UPT_MTT varchar(500),
	KODATA_UPD_DT varchar(8),
	CONO_BAD_INFO varchar(2),
	BZNO_BAD_INFO varchar(2),
	CO_REG_INFO varchar(2),
	LQDT_INFO varchar(2),
	KODATACD varchar(10),
	KODATA_ENP_NM varchar(100),
	KODATA_REPER_NM varchar(50),
	LOC varchar(6),
	ADDR1 varchar(200),
	ADDR2 varchar(200),
	TEL_NO varchar(20),
	ESTB_DT varchar(8),
	ASET_T_SUM varchar(13),
	LIAB_T_SUM varchar(13),
	SAM varchar(13),
	BZPF varchar(13),
	NPF_CT varchar(13),
	RND_MP varchar(13),
	ACCT_DT varchar(8),
	BZC_CD varchar(6),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 이노비즈인증기업
CREATE TABLE IF_50TB
(
	SN numeric(10) NOT NULL,
	BASE_DT varchar(8),
	BZNO varchar(10),
	CONO varchar(13),
	ENP_NM varchar(100),
	REPER_NM varchar(50),
	XPIR_DT varchar(8),
	EVL_IDX_NM varchar(50),
	BZC_CD_NM varchar(100),
	KODATA_UPD_DT varchar(8),
	CONO_BAD_INFO varchar(2),
	BZNO_BAD_INFO varchar(2),
	CO_REG_INFO varchar(2),
	LQDT_INFO varchar(2),
	KODATACD varchar(10),
	KODATA_ENP_NM varchar(100),
	KODATA_REPER_NM varchar(50),
	LOC varchar(6),
	ADDR1 varchar(200),
	ADDR2 varchar(200),
	TEL_NO varchar(20),
	ESTB_DT varchar(8),
	ASET_T_SUM varchar(13),
	LIAB_T_SUM varchar(13),
	SAM varchar(13),
	BZPF varchar(13),
	NPF_CT varchar(13),
	RND_MP varchar(13),
	ACCT_DT varchar(8),
	BZC_CD varchar(6),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 연구소인증기업
CREATE TABLE IF_50TF
(
	SN numeric(10) NOT NULL,
	BASE_DT varchar(8),
	BZNO varchar(10),
	CONO varchar(13),
	SEQ varchar(4),
	ENP_NM varchar(100),
	REPER_NM varchar(50),
	RSRCHI_SEQ varchar(20),
	FST_RCGN_DT varchar(8),
	BZC_CD_NM varchar(100),
	RSRCHI_NM varchar(100),
	RSRCHI_ADDR varchar(200),
	RSRCH_AFLD varchar(50),
	KODATA_UPD_DT varchar(8),
	CONO_BAD_INFO varchar(2),
	BZNO_BAD_INFO varchar(2),
	CO_REG_INFO varchar(2),
	LQDT_INFO varchar(2),
	KODATACD varchar(10),
	KODATA_ENP_NM varchar(100),
	KODATA_REPER_NM varchar(50),
	LOC varchar(6),
	ADDR1 varchar(200),
	ADDR2 varchar(200),
	TEL_NO varchar(20),
	ESTB_DT varchar(8),
	ASET_T_SUM varchar(13),
	LIAB_T_SUM varchar(13),
	SAM varchar(13),
	BZPF varchar(13),
	NPF_CT varchar(13),
	RND_MP varchar(13),
	ACCT_DT varchar(8),
	BZC_CD varchar(6),
	RSRCH_CLS_CD varchar(1),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 특허및실용신안기업-요약
CREATE TABLE IF_50TG
(
	SN numeric(10) NOT NULL,
	BASE_DT varchar(8),
	BZNO varchar(10),
	CONO varchar(13),
	PND_DSGN_CN varchar(10),
	PND_TRDK_CN varchar(10),
	REG_DSGN_CN varchar(10),
	REG_TRDK_CN varchar(10),
	REG_VLD_DSGN_CN varchar(10),
	REG_VLD_TRDK_CN varchar(10),
	KODATA_UPD_DT varchar(8),
	CONO_BAD_INFO varchar(2),
	BZNO_BAD_INFO varchar(2),
	CO_REG_INFO varchar(2),
	LQDT_INFO varchar(2),
	KODATACD varchar(10),
	KODATA_ENP_NM varchar(100),
	KODATA_REPER_NM varchar(50),
	LOC varchar(6),
	ADDR1 varchar(200),
	ADDR2 varchar(200),
	TEL_NO varchar(20),
	ESTB_DT varchar(8),
	ASET_T_SUM varchar(13),
	LIAB_T_SUM varchar(13),
	SAM varchar(13),
	BZPF varchar(13),
	NPF_CT varchar(13),
	RND_MP varchar(13),
	ACCT_DT varchar(8),
	BZC_CD varchar(6),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 특허및실용신안기업-상세
CREATE TABLE IF_50TH
(
	SN numeric(10) NOT NULL,
	BASE_DT varchar(8),
	KODATACD varchar(10),
	IND_PPT_SEQ varchar(7),
	IPR_CD varchar(2),
	REG_STAT varchar(2),
	PTNT_PND_NO varchar(30),
	PND_DT varchar(8),
	REG_NO varchar(20),
	REG_DT varchar(8),
	PND_P varchar(200),
	RGT_OWNER varchar(200),
	NM varchar(500),
	ENP_REL_CD varchar(2),
	REG_VLD_YN varchar(1),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 메인비즈인증기업
CREATE TABLE IF_50TI
(
	SN numeric(10) NOT NULL,
	BASE_DT varchar(8),
	BZNO varchar(10),
	CONO varchar(13),
	ENP_NM varchar(100),
	REPER_NM varchar(50),
	CERT_STDT varchar(8),
	CERT_XPIR_DT varchar(8),
	CERT_CAN_DT varchar(8),
	KODATA_UPD_DT varchar(8),
	CONO_BAD_INFO varchar(2),
	BZNO_BAD_INFO varchar(2),
	CO_REG_INFO varchar(2),
	LQDT_INFO varchar(2),
	KODATACD varchar(10),
	KODATA_ENP_NM varchar(100),
	KODATA_REPER_NM varchar(50),
	LOC varchar(6),
	ADDR1 varchar(200),
	ADDR2 varchar(200),
	TEL_NO varchar(20),
	ESTB_DT varchar(8),
	ASET_T_SUM varchar(13),
	LIAB_T_SUM varchar(13),
	SAM varchar(13),
	BZPF varchar(13),
	NPF_CT varchar(13),
	RND_MP varchar(13),
	ACCT_DT varchar(8),
	BZC_CD varchar(6),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 디자인권및상표권-요약
CREATE TABLE IF_50TK
(
	SN numeric(10) NOT NULL,
	BASE_DT varchar(8),
	BZNO varchar(10),
	CONO varchar(13),
	PND_DSGN_CN varchar(10),
	PND_TRDK_CN varchar(10),
	REG_DSGN_CN varchar(10),
	REG_TRDK_CN varchar(10),
	REG_VLD_DSGN_CN varchar(10),
	REG_VLD_TRDK_CN varchar(10),
	KODATA_UPD_DT varchar(8),
	CONO_BAD_INFO varchar(2),
	BZNO_BAD_INFO varchar(2),
	CO_REG_INFO varchar(2),
	LQDT_INFO varchar(2),
	KODATACD varchar(10),
	KODATA_ENP_NM varchar(100),
	KODATA_REPER_NM varchar(50),
	LOC varchar(6),
	ADDR1 varchar(200),
	ADDR2 varchar(200),
	TEL_NO varchar(20),
	ESTB_DT varchar(8),
	ASET_T_SUM varchar(13),
	LIAB_T_SUM varchar(13),
	SAM varchar(13),
	BZPF varchar(13),
	NPF_CT varchar(13),
	RND_MP varchar(13),
	ACCT_DT varchar(8),
	BZC_CD varchar(6),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;


-- 디자인권및상표권상세
CREATE TABLE IF_50TL
(
	SN numeric(10) NOT NULL,
	BASE_DT varchar(8),
	KODATACD varchar(10),
	IND_PPT_SEQ varchar(7),
	IPR_CD varchar(2),
	REG_STAT varchar(2),
	PTNT_PND_NO varchar(30),
	PND_DT varchar(8),
	REG_NO varchar(20),
	REG_DT varchar(8),
	PND_P varchar(200),
	RGT_OWNER varchar(200),
	NM varchar(500),
	ENP_REL_CD varchar(2),
	REG_VLD_YN varchar(1),
	LINK_YMD timestamp,
	LINK_STUS varchar(3),
	LINK_GRP_NO numeric(10),
	PRIMARY KEY (SN)
) WITHOUT OIDS;



/* Comments */

COMMENT ON TABLE IF_5038 IS '재무분석계정코드';
COMMENT ON COLUMN IF_5038.SN IS '일련번호';
COMMENT ON COLUMN IF_5038.ACC_CD_FULL IS '계정풀코드';
COMMENT ON COLUMN IF_5038.FS_INFO_CD IS '재무정보구분코드';
COMMENT ON COLUMN IF_5038.FS_BZC_CD IS '재무업종코드';
COMMENT ON COLUMN IF_5038.FS_CCD_ANAL IS '재무분석보고서구분코드';
COMMENT ON COLUMN IF_5038.ACC_CD IS '계정코드';
COMMENT ON COLUMN IF_5038.ACC_NM IS '계정코드명';
COMMENT ON COLUMN IF_5038.ACC_NM_ENG IS '계정코드명_영문';
COMMENT ON COLUMN IF_5038.UNT IS '단위';
COMMENT ON COLUMN IF_5038.ATHXP IS '산식';
COMMENT ON COLUMN IF_5038.ATHXP_CTT IS '산식내용';
COMMENT ON COLUMN IF_5038.PIC_CCD IS '화면구분코드';
COMMENT ON COLUMN IF_5038.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_5038.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_5038.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_5039 IS '재무분석DATA';
COMMENT ON COLUMN IF_5039.SN IS '일련번호';
COMMENT ON COLUMN IF_5039.KEDCD IS 'KED코드';
COMMENT ON COLUMN IF_5039.STTL_BASE_YM_DD IS '기준년월일';
COMMENT ON COLUMN IF_5039.FS_INFO_CD IS '재무정보구분코드';
COMMENT ON COLUMN IF_5039.ACCT_CCD IS '결산구분코드';
COMMENT ON COLUMN IF_5039.ACC_CD_FULL IS '계정풀코드';
COMMENT ON COLUMN IF_5039.VAL IS '항목값';
COMMENT ON COLUMN IF_5039.ITM_STL IS '항목문자열';
COMMENT ON COLUMN IF_5039.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_5039.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_5039.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_5041 IS '종합신용등급';
COMMENT ON COLUMN IF_5041.SN IS '일련번호';
COMMENT ON COLUMN IF_5041.KEDCD IS 'KED코드';
COMMENT ON COLUMN IF_5041.REG_DT IS '등록일자';
COMMENT ON COLUMN IF_5041.EVL_DT IS '평가일자';
COMMENT ON COLUMN IF_5041.STTL_BASE_DD IS '결산기준일';
COMMENT ON COLUMN IF_5041.GRD_CLS IS '등급구분';
COMMENT ON COLUMN IF_5041.CR_GRD IS '신용등급';
COMMENT ON COLUMN IF_5041.MODL_EVL_DT IS '모형평가일자';
COMMENT ON COLUMN IF_5041.IVG_MTD_CLS IS '조사방법구분';
COMMENT ON COLUMN IF_5041.GRD_SV_ST_DD IS '등급서비스개시일';
COMMENT ON COLUMN IF_5041.GRD_SV_EDDT IS '등급서비스종료일';
COMMENT ON COLUMN IF_5041.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_5041.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_5041.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_5056 IS '신계정_재무계정코드';
COMMENT ON COLUMN IF_5056.SN IS '일련번호';
COMMENT ON COLUMN IF_5056.ACC_CD_FULL IS '계정풀코드';
COMMENT ON COLUMN IF_5056.FS_INFO_CD IS '재무정보구분코드';
COMMENT ON COLUMN IF_5056.FS_BZC_CD IS '재무업종코드';
COMMENT ON COLUMN IF_5056.FS_CCD IS '보고서구분코드';
COMMENT ON COLUMN IF_5056.ACC_CD IS '계정코드';
COMMENT ON COLUMN IF_5056.ACC_NM IS '계정코드명';
COMMENT ON COLUMN IF_5056.ACC_NM_ENG IS '계정코드명_영문';
COMMENT ON COLUMN IF_5056.UNT IS '단위';
COMMENT ON COLUMN IF_5056.ATHXP IS '산식';
COMMENT ON COLUMN IF_5056.ATHXP_CTT IS '산식내용';
COMMENT ON COLUMN IF_5056.ACC_CD_LVL IS '재무계정레벨';
COMMENT ON COLUMN IF_5056.IVG_INP_ACC_YN IS '조사입력계정여부';
COMMENT ON COLUMN IF_5056.SMRY_FIN_YN IS '요약재무여부';
COMMENT ON COLUMN IF_5056.HELP_YN IS '도움말여부';
COMMENT ON COLUMN IF_5056.BS_SMRY_YN IS '대차대조표요약여부';
COMMENT ON COLUMN IF_5056.MUS_YN IS '음수계정불능여부';
COMMENT ON COLUMN IF_5056.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_5056.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_5056.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_5057 IS '신계정_재무제표MASTER';
COMMENT ON COLUMN IF_5057.SN IS '일련번호';
COMMENT ON COLUMN IF_5057.KEDCD IS 'KED코드';
COMMENT ON COLUMN IF_5057.ACCT_DT IS '결산기준연월일';
COMMENT ON COLUMN IF_5057.FS_CCD IS '보고서구분코드';
COMMENT ON COLUMN IF_5057.ACCT_CCD IS '결산구분코드';
COMMENT ON COLUMN IF_5057.ACCT_STDT IS '결산시작일자';
COMMENT ON COLUMN IF_5057.ACCT_EDDT IS '결산종료일자';
COMMENT ON COLUMN IF_5057.FS_INFO_CD IS '재무정보구분코드';
COMMENT ON COLUMN IF_5057.FS_BZC_CD IS '재무업종코드';
COMMENT ON COLUMN IF_5057.BOOK_ETRY_CCD IS '장부기장구분코드';
COMMENT ON COLUMN IF_5057.WRT_BAS_CD IS '작성근거';
COMMENT ON COLUMN IF_5057.TRF_YN IS '재무제표변환여부';
COMMENT ON COLUMN IF_5057.STD_DT IS '정보기준일자';
COMMENT ON COLUMN IF_5057.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_5057.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_5057.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_5058 IS '신계정_재무제표DATA';
COMMENT ON COLUMN IF_5058.SN IS '일련번호';
COMMENT ON COLUMN IF_5058.KEDCD IS 'KED코드';
COMMENT ON COLUMN IF_5058.ACCT_DT IS '결산기준연월일';
COMMENT ON COLUMN IF_5058.FS_CCD IS '보고서구분코드';
COMMENT ON COLUMN IF_5058.ACCT_CCD IS '결산구분코드';
COMMENT ON COLUMN IF_5058.ACC_CD_FULL IS '계정풀코드';
COMMENT ON COLUMN IF_5058.VAL IS '항목값';
COMMENT ON COLUMN IF_5058.RT IS '구성비';
COMMENT ON COLUMN IF_5058.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_5058.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_5058.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_5062 IS '(신회계)재무비율계정코드';
COMMENT ON COLUMN IF_5062.SN IS '일련번호';
COMMENT ON COLUMN IF_5062.ACC_CD_FULL IS '계정풀코드';
COMMENT ON COLUMN IF_5062.FS_INFO_CD IS '재무정보구분코드';
COMMENT ON COLUMN IF_5062.FS_BZC_CD IS '재무업종코드';
COMMENT ON COLUMN IF_5062.FS_CCD_RT IS '재무비율보고서구분코드';
COMMENT ON COLUMN IF_5062.ACC_CD IS '계정코드';
COMMENT ON COLUMN IF_5062.ACC_NM IS '계정코드명';
COMMENT ON COLUMN IF_5062.ACC_NM_ENG IS '계정코드명_영문';
COMMENT ON COLUMN IF_5062.UNT IS '단위';
COMMENT ON COLUMN IF_5062.ATHXP IS '산식';
COMMENT ON COLUMN IF_5062.ATHXP_CTT IS '산식내용';
COMMENT ON COLUMN IF_5062.QT_CRE_CCD IS '분기생성여부';
COMMENT ON COLUMN IF_5062.PRD_CRE_CCD IS '기간생성여부';
COMMENT ON COLUMN IF_5062.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_5062.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_5062.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_5063 IS '(신회계)재무비율DATA';
COMMENT ON COLUMN IF_5063.SN IS '일련번호';
COMMENT ON COLUMN IF_5063.KEDCD IS 'KED코드';
COMMENT ON COLUMN IF_5063.ACCT_DT IS '기준년월일';
COMMENT ON COLUMN IF_5063.ACCT_CCD IS '결산구분코드';
COMMENT ON COLUMN IF_5063.ACC_CD_FULL IS '계정풀코드';
COMMENT ON COLUMN IF_5063.FS_INFO_CD IS '재무정보구분코드';
COMMENT ON COLUMN IF_5063.FS_BZC_CD IS '재무업종코드';
COMMENT ON COLUMN IF_5063.FS_CCD IS '보고서구분코드';
COMMENT ON COLUMN IF_5063.ACC_CD IS '계정코드';
COMMENT ON COLUMN IF_5063.VAL IS '항목값';
COMMENT ON COLUMN IF_5063.ERR_CD IS '산출오류코드';
COMMENT ON COLUMN IF_5063.STD_DT IS '정보기준일자';
COMMENT ON COLUMN IF_5063.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_5063.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_5063.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_50D1 IS '업체개요';
COMMENT ON COLUMN IF_50D1.SN IS '일련번호';
COMMENT ON COLUMN IF_50D1.KEDCD IS 'KED코드';
COMMENT ON COLUMN IF_50D1.ENP_NM IS '기업체명';
COMMENT ON COLUMN IF_50D1.ENP_NM_TRD IS '기업체TradeName';
COMMENT ON COLUMN IF_50D1.ENP_NM_ENG IS '기업체명 영문';
COMMENT ON COLUMN IF_50D1.ENP_TYP IS '기업유형';
COMMENT ON COLUMN IF_50D1.ENP_SZE IS '기업규모';
COMMENT ON COLUMN IF_50D1.GRDT_PLN_DT IS '졸업예정일';
COMMENT ON COLUMN IF_50D1.ENP_FCD IS '기업형태코드';
COMMENT ON COLUMN IF_50D1.ESTB_FCD IS '설립형태';
COMMENT ON COLUMN IF_50D1.ENP_SCD IS '기업상태';
COMMENT ON COLUMN IF_50D1.ENP_SCD_CHG_DT IS '기업상태변동일';
COMMENT ON COLUMN IF_50D1.PUBI_FCD IS '정부및공공기관구분';
COMMENT ON COLUMN IF_50D1.VENP_YN IS '벤쳐기업유무';
COMMENT ON COLUMN IF_50D1.ENP_FORM_FR IS '기업형태앞뒤구분';
COMMENT ON COLUMN IF_50D1.BZC_CD IS '업종코드';
COMMENT ON COLUMN IF_50D1.FS_BZC_CD IS '재무업종코드';
COMMENT ON COLUMN IF_50D1.GRP_CD IS '그룹코드';
COMMENT ON COLUMN IF_50D1.GRP_NM IS '그룹명';
COMMENT ON COLUMN IF_50D1.CONO_PID IS '법인_주민등록번호';
COMMENT ON COLUMN IF_50D1.ESTB_DT IS '설립일자';
COMMENT ON COLUMN IF_50D1.IPO_CD IS '기업공개코드';
COMMENT ON COLUMN IF_50D1.TRDBZ_RPT_NO IS '무역업신고번호';
COMMENT ON COLUMN IF_50D1.LIST_DT IS '상장일자';
COMMENT ON COLUMN IF_50D1.DLIST_DT IS '상장폐지일자';
COMMENT ON COLUMN IF_50D1.MTX_BNK_CD IS '주거래여신기관코드';
COMMENT ON COLUMN IF_50D1.MTX_BNK_NM IS '주거래여신기관명';
COMMENT ON COLUMN IF_50D1.OVD_TX_BNK_CD IS '당좌거래은행코드';
COMMENT ON COLUMN IF_50D1.OVD_TX_BNK_NM IS '당좌거래은행명';
COMMENT ON COLUMN IF_50D1.ACCT_EDDT IS '결산기준월일';
COMMENT ON COLUMN IF_50D1.HPAGE_URL IS '홈페이지';
COMMENT ON COLUMN IF_50D1.EMAIL IS '이메일';
COMMENT ON COLUMN IF_50D1.STD_DT IS '정보기준일자';
COMMENT ON COLUMN IF_50D1.BZNO IS '사업자번호';
COMMENT ON COLUMN IF_50D1.LOC_ZIP IS '소재지우편번호';
COMMENT ON COLUMN IF_50D1.LOC_ADDRA IS '소재지우편번호주소';
COMMENT ON COLUMN IF_50D1.LOC_ADDRB IS '소재지_나머지주소';
COMMENT ON COLUMN IF_50D1.TEL_NO IS '전화번호';
COMMENT ON COLUMN IF_50D1.FAX_NO IS '팩스번호';
COMMENT ON COLUMN IF_50D1.LABORER_SUM IS '상시근로자수(합계)';
COMMENT ON COLUMN IF_50D1.PD_NM IS '제품명';
COMMENT ON COLUMN IF_50D1.KSIC9_BZC_CD IS '업종코드';
COMMENT ON COLUMN IF_50D1.REL_KEDCD IS '관련기업KED코드';
COMMENT ON COLUMN IF_50D1.REL_ESTB_DT IS '관련기업설립일';
COMMENT ON COLUMN IF_50D1.LOC_RDNM_ZIP IS '도로명소재지우편번호';
COMMENT ON COLUMN IF_50D1.LOC_RDNM_ADDRA IS '도로명소재지우편번호주소';
COMMENT ON COLUMN IF_50D1.LOC_RDNM_ADDRB IS '도로명소재지우편번호이하주소';
COMMENT ON COLUMN IF_50D1.LOC_RDNM_ADDRB_CONF_YN IS '도로명소재지주소확인여부';
COMMENT ON COLUMN IF_50D1.LOC_ADDRB_CONF_YN IS '소재지주소확인여부';
COMMENT ON COLUMN IF_50D1.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_50D1.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_50D1.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_50D2 IS '대표자정보';
COMMENT ON COLUMN IF_50D2.SN IS '일련번호';
COMMENT ON COLUMN IF_50D2.KEDCD IS 'KED코드';
COMMENT ON COLUMN IF_50D2.PCD IS '인물코드';
COMMENT ON COLUMN IF_50D2.STD_DT IS '정보기준일자';
COMMENT ON COLUMN IF_50D2.NAME IS '성명';
COMMENT ON COLUMN IF_50D2.PID IS '주민등록번호';
COMMENT ON COLUMN IF_50D2.REPER_CCD IS '대표자구분코드';
COMMENT ON COLUMN IF_50D2.MRK_REPER_YN IS '표시대표자여부';
COMMENT ON COLUMN IF_50D2.ASMP_DT IS '취임일자';
COMMENT ON COLUMN IF_50D2.RTIR_DT IS '퇴임일자';
COMMENT ON COLUMN IF_50D2.PO_YN IS '현직여부';
COMMENT ON COLUMN IF_50D2.TTL IS '직위';
COMMENT ON COLUMN IF_50D2.MNG_FCD IS '경영형태코드';
COMMENT ON COLUMN IF_50D2.SBZC_EG_YCN_REPER IS '동업계종사연수대표자';
COMMENT ON COLUMN IF_50D2.SBZC_EG_MCN_REPER IS '동업계종사월수대표자';
COMMENT ON COLUMN IF_50D2.SIND_EG_PRD_YY IS '동업계종사기간년';
COMMENT ON COLUMN IF_50D2.SIND_EG_PRD_MM IS '동업계종사기간월';
COMMENT ON COLUMN IF_50D2.SBZC_EVL_CD IS '동업계평코드';
COMMENT ON COLUMN IF_50D2.MDM_REL_CD IS '경영실권자와의관계코드';
COMMENT ON COLUMN IF_50D2.REPER_MABL_CD IS '경영능력코드';
COMMENT ON COLUMN IF_50D2.CSTK_OWN IS '주식소유현황(보통주)';
COMMENT ON COLUMN IF_50D2.PSTK_OWN IS '주식소유현황(우선주)';
COMMENT ON COLUMN IF_50D2.SO_REG_CN IS '스톡옵션부여(주식수)';
COMMENT ON COLUMN IF_50D2.RMK IS '비고';
COMMENT ON COLUMN IF_50D2.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_50D2.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_50D2.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_50PA IS '국민연금정보(국민연금월별정보현황)';
COMMENT ON COLUMN IF_50PA.SN IS '일련번호';
COMMENT ON COLUMN IF_50PA.KEDCD IS 'KED코드';
COMMENT ON COLUMN IF_50PA.DATA_CRE_YM IS '자료생성년월';
COMMENT ON COLUMN IF_50PA.JOIN_PRS_CN IS '가입자수';
COMMENT ON COLUMN IF_50PA.TMONNTTC_AM IS '당월고지금액';
COMMENT ON COLUMN IF_50PA.MONTY_NMFEMP IS '월별취업자수';
COMMENT ON COLUMN IF_50PA.MM_CFB_RTIR_PRS_CN IS '월별퇴직자수';
COMMENT ON COLUMN IF_50PA.AVG_SLRY_PE IS '1인평균년간급여(합계)';
COMMENT ON COLUMN IF_50PA.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_50PA.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_50PA.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_50TA IS '벤처인증기업';
COMMENT ON COLUMN IF_50TA.SN IS '일련번호';
COMMENT ON COLUMN IF_50TA.BASE_DT IS '기준일자';
COMMENT ON COLUMN IF_50TA.BZNO IS '사업자번호';
COMMENT ON COLUMN IF_50TA.CONO IS '법인번호';
COMMENT ON COLUMN IF_50TA.ENP_NM IS '업체명';
COMMENT ON COLUMN IF_50TA.MAI_GDSNM1 IS '주요제품명';
COMMENT ON COLUMN IF_50TA.VNTRBZ_CFMT_DV IS '벤처기업확인서발급일';
COMMENT ON COLUMN IF_50TA.VNTR_STRT_VLDYMD IS '벤처기업확인서시작일';
COMMENT ON COLUMN IF_50TA.VNTR_EN_VLDYMD IS '벤처기업확인서유효기간만료일';
COMMENT ON COLUMN IF_50TA.UPT_MTT IS '변경사항';
COMMENT ON COLUMN IF_50TA.KODATA_UPD_DT IS '업데이트일자';
COMMENT ON COLUMN IF_50TA.CONO_BAD_INFO IS '법인번호채무불이행정보';
COMMENT ON COLUMN IF_50TA.BZNO_BAD_INFO IS '사업자번호채무불이행정보';
COMMENT ON COLUMN IF_50TA.CO_REG_INFO IS '법인등기정보';
COMMENT ON COLUMN IF_50TA.LQDT_INFO IS '휴폐업정보';
COMMENT ON COLUMN IF_50TA.KODATACD IS 'KoDATA코드';
COMMENT ON COLUMN IF_50TA.KODATA_ENP_NM IS 'KoDATA업체명';
COMMENT ON COLUMN IF_50TA.KODATA_REPER_NM IS 'KoDATA대표자명';
COMMENT ON COLUMN IF_50TA.LOC IS '우편번호';
COMMENT ON COLUMN IF_50TA.ADDR1 IS '주소1';
COMMENT ON COLUMN IF_50TA.ADDR2 IS '주소2';
COMMENT ON COLUMN IF_50TA.TEL_NO IS '전화번호';
COMMENT ON COLUMN IF_50TA.ESTB_DT IS '설립일자';
COMMENT ON COLUMN IF_50TA.ASET_T_SUM IS '자산총액(천원)';
COMMENT ON COLUMN IF_50TA.LIAB_T_SUM IS '부채총액(천원)';
COMMENT ON COLUMN IF_50TA.SAM IS '매출액(천원)';
COMMENT ON COLUMN IF_50TA.BZPF IS '영업이익(천원)';
COMMENT ON COLUMN IF_50TA.NPF_CT IS '당기순이익(천원)';
COMMENT ON COLUMN IF_50TA.RND_MP IS '연구개발비(천원)';
COMMENT ON COLUMN IF_50TA.ACCT_DT IS '재무기준일';
COMMENT ON COLUMN IF_50TA.BZC_CD IS '표준산업분류코드';
COMMENT ON COLUMN IF_50TA.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_50TA.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_50TA.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_50TB IS '이노비즈인증기업';
COMMENT ON COLUMN IF_50TB.SN IS '일련번호';
COMMENT ON COLUMN IF_50TB.BASE_DT IS '기준일자';
COMMENT ON COLUMN IF_50TB.BZNO IS '사업자번호';
COMMENT ON COLUMN IF_50TB.CONO IS '법인번호';
COMMENT ON COLUMN IF_50TB.ENP_NM IS '업체명';
COMMENT ON COLUMN IF_50TB.REPER_NM IS '대표자명';
COMMENT ON COLUMN IF_50TB.XPIR_DT IS '인증만료일자';
COMMENT ON COLUMN IF_50TB.EVL_IDX_NM IS '평가지표명';
COMMENT ON COLUMN IF_50TB.BZC_CD_NM IS '업종명';
COMMENT ON COLUMN IF_50TB.KODATA_UPD_DT IS '업데이트일자';
COMMENT ON COLUMN IF_50TB.CONO_BAD_INFO IS '법인번호채무불이행정보';
COMMENT ON COLUMN IF_50TB.BZNO_BAD_INFO IS '사업자번호채무불이행정보';
COMMENT ON COLUMN IF_50TB.CO_REG_INFO IS '법인등기정보';
COMMENT ON COLUMN IF_50TB.LQDT_INFO IS '휴폐업정보';
COMMENT ON COLUMN IF_50TB.KODATACD IS 'KoDATA코드';
COMMENT ON COLUMN IF_50TB.KODATA_ENP_NM IS 'KoDATA업체명';
COMMENT ON COLUMN IF_50TB.KODATA_REPER_NM IS 'KoDATA대표자명';
COMMENT ON COLUMN IF_50TB.LOC IS '우편번호';
COMMENT ON COLUMN IF_50TB.ADDR1 IS '주소1';
COMMENT ON COLUMN IF_50TB.ADDR2 IS '주소2';
COMMENT ON COLUMN IF_50TB.TEL_NO IS '전화번호';
COMMENT ON COLUMN IF_50TB.ESTB_DT IS '설립일자';
COMMENT ON COLUMN IF_50TB.ASET_T_SUM IS '자산총액(천원)';
COMMENT ON COLUMN IF_50TB.LIAB_T_SUM IS '부채총액(천원)';
COMMENT ON COLUMN IF_50TB.SAM IS '매출액(천원)';
COMMENT ON COLUMN IF_50TB.BZPF IS '영업이익(천원)';
COMMENT ON COLUMN IF_50TB.NPF_CT IS '당기순이익(천원)';
COMMENT ON COLUMN IF_50TB.RND_MP IS '연구개발비(천원)';
COMMENT ON COLUMN IF_50TB.ACCT_DT IS '재무기준일';
COMMENT ON COLUMN IF_50TB.BZC_CD IS '표준산업분류코드';
COMMENT ON COLUMN IF_50TB.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_50TB.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_50TB.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_50TF IS '연구소인증기업';
COMMENT ON COLUMN IF_50TF.SN IS '일련번호';
COMMENT ON COLUMN IF_50TF.BASE_DT IS '기준일자';
COMMENT ON COLUMN IF_50TF.BZNO IS '사업자번호';
COMMENT ON COLUMN IF_50TF.CONO IS '법인번호';
COMMENT ON COLUMN IF_50TF.SEQ IS 'KoDATA일련번호';
COMMENT ON COLUMN IF_50TF.ENP_NM IS '업체명';
COMMENT ON COLUMN IF_50TF.REPER_NM IS '대표자명';
COMMENT ON COLUMN IF_50TF.RSRCHI_SEQ IS '연구소일련번호';
COMMENT ON COLUMN IF_50TF.FST_RCGN_DT IS '최초인정일자';
COMMENT ON COLUMN IF_50TF.BZC_CD_NM IS '업종명';
COMMENT ON COLUMN IF_50TF.RSRCHI_NM IS '연구소(전담부서)명';
COMMENT ON COLUMN IF_50TF.RSRCHI_ADDR IS '연구소소재지';
COMMENT ON COLUMN IF_50TF.RSRCH_AFLD IS '연구분야';
COMMENT ON COLUMN IF_50TF.KODATA_UPD_DT IS '업데이트일자';
COMMENT ON COLUMN IF_50TF.CONO_BAD_INFO IS '법인번호채무불이행정보';
COMMENT ON COLUMN IF_50TF.BZNO_BAD_INFO IS '사업자번호채무불이행정보';
COMMENT ON COLUMN IF_50TF.CO_REG_INFO IS '법인등기정보';
COMMENT ON COLUMN IF_50TF.LQDT_INFO IS '휴폐업정보';
COMMENT ON COLUMN IF_50TF.KODATACD IS 'KoDATA코드';
COMMENT ON COLUMN IF_50TF.KODATA_ENP_NM IS 'KoDATA업체명';
COMMENT ON COLUMN IF_50TF.KODATA_REPER_NM IS 'KoDATA대표자명';
COMMENT ON COLUMN IF_50TF.LOC IS '우편번호';
COMMENT ON COLUMN IF_50TF.ADDR1 IS '주소1';
COMMENT ON COLUMN IF_50TF.ADDR2 IS '주소2';
COMMENT ON COLUMN IF_50TF.TEL_NO IS '전화번호';
COMMENT ON COLUMN IF_50TF.ESTB_DT IS '설립일자';
COMMENT ON COLUMN IF_50TF.ASET_T_SUM IS '자산총액(천원)';
COMMENT ON COLUMN IF_50TF.LIAB_T_SUM IS '부채총액(천원)';
COMMENT ON COLUMN IF_50TF.SAM IS '매출액(천원)';
COMMENT ON COLUMN IF_50TF.BZPF IS '영업이익(천원)';
COMMENT ON COLUMN IF_50TF.NPF_CT IS '당기순이익(천원)';
COMMENT ON COLUMN IF_50TF.RND_MP IS '연구개발비(천원)';
COMMENT ON COLUMN IF_50TF.ACCT_DT IS '재무기준일';
COMMENT ON COLUMN IF_50TF.BZC_CD IS '표준산업분류코드';
COMMENT ON COLUMN IF_50TF.RSRCH_CLS_CD IS '연구소구분코드';
COMMENT ON COLUMN IF_50TF.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_50TF.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_50TF.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_50TG IS '특허및실용신안기업-요약';
COMMENT ON COLUMN IF_50TG.SN IS '일련번호';
COMMENT ON COLUMN IF_50TG.BASE_DT IS '기준일자';
COMMENT ON COLUMN IF_50TG.BZNO IS '사업자번호';
COMMENT ON COLUMN IF_50TG.CONO IS '법인번호';
COMMENT ON COLUMN IF_50TG.PND_DSGN_CN IS '디자인출원한건수';
COMMENT ON COLUMN IF_50TG.PND_TRDK_CN IS '상표권출원한건수';
COMMENT ON COLUMN IF_50TG.REG_DSGN_CN IS '디자인권출원후등록된건수';
COMMENT ON COLUMN IF_50TG.REG_TRDK_CN IS '상표권출원후등록된건수';
COMMENT ON COLUMN IF_50TG.REG_VLD_DSGN_CN IS '디자인권등록건중유효한건수';
COMMENT ON COLUMN IF_50TG.REG_VLD_TRDK_CN IS '상표권등록건중유효한건수';
COMMENT ON COLUMN IF_50TG.KODATA_UPD_DT IS '업데이트일자';
COMMENT ON COLUMN IF_50TG.CONO_BAD_INFO IS '법인번호채무불이행정보';
COMMENT ON COLUMN IF_50TG.BZNO_BAD_INFO IS '사업자번호채무불이행정보';
COMMENT ON COLUMN IF_50TG.CO_REG_INFO IS '법인등기정보';
COMMENT ON COLUMN IF_50TG.LQDT_INFO IS '휴폐업정보';
COMMENT ON COLUMN IF_50TG.KODATACD IS 'KoDATA코드';
COMMENT ON COLUMN IF_50TG.KODATA_ENP_NM IS 'KoDATA업체명';
COMMENT ON COLUMN IF_50TG.KODATA_REPER_NM IS 'KoDATA대표자명';
COMMENT ON COLUMN IF_50TG.LOC IS '우편번호';
COMMENT ON COLUMN IF_50TG.ADDR1 IS '주소1';
COMMENT ON COLUMN IF_50TG.ADDR2 IS '주소2';
COMMENT ON COLUMN IF_50TG.TEL_NO IS '전화번호';
COMMENT ON COLUMN IF_50TG.ESTB_DT IS '설립일자';
COMMENT ON COLUMN IF_50TG.ASET_T_SUM IS '자산총액(천원)';
COMMENT ON COLUMN IF_50TG.LIAB_T_SUM IS '부채총액(천원)';
COMMENT ON COLUMN IF_50TG.SAM IS '매출액(천원)';
COMMENT ON COLUMN IF_50TG.BZPF IS '영업이익(천원)';
COMMENT ON COLUMN IF_50TG.NPF_CT IS '당기순이익(천원)';
COMMENT ON COLUMN IF_50TG.RND_MP IS '연구개발비(천원)';
COMMENT ON COLUMN IF_50TG.ACCT_DT IS '재무기준일';
COMMENT ON COLUMN IF_50TG.BZC_CD IS '표준산업분류코드';
COMMENT ON COLUMN IF_50TG.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_50TG.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_50TG.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_50TH IS '특허및실용신안기업-상세';
COMMENT ON COLUMN IF_50TH.SN IS '일련번호';
COMMENT ON COLUMN IF_50TH.BASE_DT IS '기준일자';
COMMENT ON COLUMN IF_50TH.KODATACD IS 'KoDATA코드';
COMMENT ON COLUMN IF_50TH.IND_PPT_SEQ IS '지적재산권일련번호';
COMMENT ON COLUMN IF_50TH.IPR_CD IS '지적재산권종류';
COMMENT ON COLUMN IF_50TH.REG_STAT IS '등록상태';
COMMENT ON COLUMN IF_50TH.PTNT_PND_NO IS '지적재산권출원번호';
COMMENT ON COLUMN IF_50TH.PND_DT IS '지적재산권출원일자';
COMMENT ON COLUMN IF_50TH.REG_NO IS '지적재산권등록번호';
COMMENT ON COLUMN IF_50TH.REG_DT IS '지적재산권등록일자';
COMMENT ON COLUMN IF_50TH.PND_P IS '출원인';
COMMENT ON COLUMN IF_50TH.RGT_OWNER IS '권리권자';
COMMENT ON COLUMN IF_50TH.NM IS '명칭';
COMMENT ON COLUMN IF_50TH.ENP_REL_CD IS '회사와의관계코드';
COMMENT ON COLUMN IF_50TH.REG_VLD_YN IS '등록유효여부';
COMMENT ON COLUMN IF_50TH.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_50TH.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_50TH.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_50TI IS '메인비즈인증기업';
COMMENT ON COLUMN IF_50TI.SN IS '일련번호';
COMMENT ON COLUMN IF_50TI.BASE_DT IS '기준일자';
COMMENT ON COLUMN IF_50TI.BZNO IS '사업자번호';
COMMENT ON COLUMN IF_50TI.CONO IS '법인번호';
COMMENT ON COLUMN IF_50TI.ENP_NM IS '업체명';
COMMENT ON COLUMN IF_50TI.REPER_NM IS '대표자명';
COMMENT ON COLUMN IF_50TI.CERT_STDT IS '인증시작일자';
COMMENT ON COLUMN IF_50TI.CERT_XPIR_DT IS '인증만료일자';
COMMENT ON COLUMN IF_50TI.CERT_CAN_DT IS '인증취소일자';
COMMENT ON COLUMN IF_50TI.KODATA_UPD_DT IS '업데이트일자';
COMMENT ON COLUMN IF_50TI.CONO_BAD_INFO IS '법인번호채무불이행정보';
COMMENT ON COLUMN IF_50TI.BZNO_BAD_INFO IS '사업자번호채무불이행정보';
COMMENT ON COLUMN IF_50TI.CO_REG_INFO IS '법인등기정보';
COMMENT ON COLUMN IF_50TI.LQDT_INFO IS '휴폐업정보';
COMMENT ON COLUMN IF_50TI.KODATACD IS 'KoDATA코드';
COMMENT ON COLUMN IF_50TI.KODATA_ENP_NM IS 'KoDATA업체명';
COMMENT ON COLUMN IF_50TI.KODATA_REPER_NM IS 'KoDATA대표자명';
COMMENT ON COLUMN IF_50TI.LOC IS '우편번호';
COMMENT ON COLUMN IF_50TI.ADDR1 IS '주소1';
COMMENT ON COLUMN IF_50TI.ADDR2 IS '주소2';
COMMENT ON COLUMN IF_50TI.TEL_NO IS '전화번호';
COMMENT ON COLUMN IF_50TI.ESTB_DT IS '설립일자';
COMMENT ON COLUMN IF_50TI.ASET_T_SUM IS '자산총액(천원)';
COMMENT ON COLUMN IF_50TI.LIAB_T_SUM IS '부채총액(천원)';
COMMENT ON COLUMN IF_50TI.SAM IS '매출액(천원)';
COMMENT ON COLUMN IF_50TI.BZPF IS '영업이익(천원)';
COMMENT ON COLUMN IF_50TI.NPF_CT IS '당기순이익(천원)';
COMMENT ON COLUMN IF_50TI.RND_MP IS '연구개발비(천원)';
COMMENT ON COLUMN IF_50TI.ACCT_DT IS '재무기준일';
COMMENT ON COLUMN IF_50TI.BZC_CD IS '표준산업분류코드';
COMMENT ON COLUMN IF_50TI.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_50TI.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_50TI.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_50TK IS '디자인권및상표권-요약';
COMMENT ON COLUMN IF_50TK.SN IS '일련번호';
COMMENT ON COLUMN IF_50TK.BASE_DT IS '기준일자';
COMMENT ON COLUMN IF_50TK.BZNO IS '사업자번호';
COMMENT ON COLUMN IF_50TK.CONO IS '법인번호';
COMMENT ON COLUMN IF_50TK.PND_DSGN_CN IS '디자인출원한건수';
COMMENT ON COLUMN IF_50TK.PND_TRDK_CN IS '상표권출원한건수';
COMMENT ON COLUMN IF_50TK.REG_DSGN_CN IS '디자인권출원후등록된건수';
COMMENT ON COLUMN IF_50TK.REG_TRDK_CN IS '상표권출원후등록된건수';
COMMENT ON COLUMN IF_50TK.REG_VLD_DSGN_CN IS '디자인권등록건중유효한건수';
COMMENT ON COLUMN IF_50TK.REG_VLD_TRDK_CN IS '상표권등록건중유효한건수';
COMMENT ON COLUMN IF_50TK.KODATA_UPD_DT IS '업데이트일자';
COMMENT ON COLUMN IF_50TK.CONO_BAD_INFO IS '법인번호채무불이행정보';
COMMENT ON COLUMN IF_50TK.BZNO_BAD_INFO IS '사업자번호채무불이행정보';
COMMENT ON COLUMN IF_50TK.CO_REG_INFO IS '법인등기정보';
COMMENT ON COLUMN IF_50TK.LQDT_INFO IS '휴폐업정보';
COMMENT ON COLUMN IF_50TK.KODATACD IS 'KoDATA코드';
COMMENT ON COLUMN IF_50TK.KODATA_ENP_NM IS 'KoDATA업체명';
COMMENT ON COLUMN IF_50TK.KODATA_REPER_NM IS 'KoDATA대표자명';
COMMENT ON COLUMN IF_50TK.LOC IS '우편번호';
COMMENT ON COLUMN IF_50TK.ADDR1 IS '주소1';
COMMENT ON COLUMN IF_50TK.ADDR2 IS '주소2';
COMMENT ON COLUMN IF_50TK.TEL_NO IS '전화번호';
COMMENT ON COLUMN IF_50TK.ESTB_DT IS '설립일자';
COMMENT ON COLUMN IF_50TK.ASET_T_SUM IS '자산총액(천원)';
COMMENT ON COLUMN IF_50TK.LIAB_T_SUM IS '부채총액(천원)';
COMMENT ON COLUMN IF_50TK.SAM IS '매출액(천원)';
COMMENT ON COLUMN IF_50TK.BZPF IS '영업이익(천원)';
COMMENT ON COLUMN IF_50TK.NPF_CT IS '당기순이익(천원)';
COMMENT ON COLUMN IF_50TK.RND_MP IS '연구개발비(천원)';
COMMENT ON COLUMN IF_50TK.ACCT_DT IS '재무기준일';
COMMENT ON COLUMN IF_50TK.BZC_CD IS '표준산업분류코드';
COMMENT ON COLUMN IF_50TK.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_50TK.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_50TK.LINK_GRP_NO IS '연계그룹번호';
COMMENT ON TABLE IF_50TL IS '디자인권및상표권상세';
COMMENT ON COLUMN IF_50TL.SN IS '일련번호';
COMMENT ON COLUMN IF_50TL.BASE_DT IS '기준일자';
COMMENT ON COLUMN IF_50TL.KODATACD IS 'KoDATA코드';
COMMENT ON COLUMN IF_50TL.IND_PPT_SEQ IS '지적재산권일련번호';
COMMENT ON COLUMN IF_50TL.IPR_CD IS '지적재산권종류';
COMMENT ON COLUMN IF_50TL.REG_STAT IS '등록상태';
COMMENT ON COLUMN IF_50TL.PTNT_PND_NO IS '지적재산권출원번호';
COMMENT ON COLUMN IF_50TL.PND_DT IS '지적재산권출원일자';
COMMENT ON COLUMN IF_50TL.REG_NO IS '지적재산권등록번호';
COMMENT ON COLUMN IF_50TL.REG_DT IS '지적재산권등록일자';
COMMENT ON COLUMN IF_50TL.PND_P IS '출원인';
COMMENT ON COLUMN IF_50TL.RGT_OWNER IS '권리권자';
COMMENT ON COLUMN IF_50TL.NM IS '명칭';
COMMENT ON COLUMN IF_50TL.ENP_REL_CD IS '회사와의관계코드';
COMMENT ON COLUMN IF_50TL.REG_VLD_YN IS '등록유효여부';
COMMENT ON COLUMN IF_50TL.LINK_YMD IS '연계일자';
COMMENT ON COLUMN IF_50TL.LINK_STUS IS '연계상태';
COMMENT ON COLUMN IF_50TL.LINK_GRP_NO IS '연계그룹번호';



