/**
	투자신청 첨부파일 (투자유치 전, 현장코칭, 컨설팅비용, 수수료)
*/		   
INSERT INTO TB_BIZ_FILE (
	  SN
	, TASK_SE_CD
	, DOC_NO
	, FILE_SE_CD
	, DCMNT_CD
	, FILE_PATH
	, STRG_FILE_NM
	, FILE_NM
	, DEL_YN
	, RGTR_NO
	, REG_YMD
)
SELECT (ROW_NUMBER() OVER(ORDER BY SEQ))+2000								AS RNUM  
	 , 'TS004'																AS TASK_SE_CD
	 , 'S'||SUBSTR(CREATE_DATE, 3,2)||LPAD(COALESCE(SEQ::TEXT,'1'),7,'0')	AS SPRT_APLY_NO
	 , '01'																	AS FILE_SE_CD
	 , CASE WHEN GB = '2' THEN 'D00A01'
	 		WHEN GB = '4' AND NUM = '1'  THEN 'D02A01'
			WHEN GB = '4' AND NUM = '2'  THEN 'D02A02'
			WHEN GB = '4' AND NUM = '3'  THEN 'D02A03'
			WHEN GB = '4' AND NUM = '4'  THEN 'D02A04'
			WHEN GB = '5' AND NUM = '1'  THEN 'D02B00'
			WHEN GB = '5' AND NUM = '2'  THEN 'D02B01'
			WHEN GB = '5' AND NUM = '3'  THEN 'D02B02'
			WHEN GB = '5' AND NUM = '4'  THEN 'D02B03'
			WHEN GB = '5' AND NUM = '5'  THEN 'D02B04'
			WHEN GB = '5' AND NUM = '6'  THEN 'D02B05'
			WHEN GB = '5' AND NUM = '7'  THEN 'D02B06'
			WHEN GB = '5' AND NUM = '8'  THEN 'D02B07'
			WHEN GB = '5' AND NUM = '9'  THEN 'D02B08'
			WHEN GB = '6' AND NUM = '1'	 THEN 'D02C00'
			WHEN GB = '6' AND NUM = '2'	 THEN 'D02C01'
			WHEN GB = '6' AND NUM = '3'	 THEN 'D02C01'
			WHEN GB = '6' AND NUM = '4'	 THEN 'D02C01'
			WHEN GB = '6' AND NUM = '5'	 THEN 'D02C01'
			WHEN GB = '6' AND NUM = '6'	 THEN 'D02C01'
			WHEN GB = '6' AND NUM = '7'	 THEN 'D02C01'
			WHEN GB = '6' AND NUM = '8'	 THEN 'D02C01'
	    END																	AS DCMNT_CD
	 , '/inveseum/request/'||SPLIT_PART(APP_FILE_NAME, '/', 2)				AS FILE_PATH
	 , SPLIT_PART(APP_FILE_NAME, '/', 3)									AS STRG_FILE_NM
	 , APP_ORIGINAL_NAME													AS FILE_NM
	 , 'N'
	 , '100000'
	 , CAST(CREATE_DATE 	AS timestamp)									AS REG_YMD
  FROM (
		SELECT SEQ, GB, '1' AS NUM, APP_FILE_NAME, APP_ORIGINAL_NAME, CREATE_DATE
		  FROM ZTB_REQUEST
		UNION ALL
		SELECT SEQ, GB, '2', APP_FILE_NAME2, APP_ORIGINAL_NAME2, CREATE_DATE
		  FROM ZTB_REQUEST
		UNION ALL
		SELECT SEQ, GB, '3', APP_FILE_NAME3, APP_ORIGINAL_NAME3, CREATE_DATE
		  FROM ZTB_REQUEST
		UNION ALL
		SELECT SEQ, GB, '4', APP_FILE_NAME4, APP_ORIGINAL_NAME4, CREATE_DATE
		  FROM ZTB_REQUEST
		UNION ALL
		SELECT SEQ, GB, '5', APP_FILE_NAME5, APP_ORIGINAL_NAME5, CREATE_DATE
		  FROM ZTB_REQUEST
		UNION ALL
		SELECT SEQ, GB, '6', APP_FILE_NAME6, APP_ORIGINAL_NAME6, CREATE_DATE
		  FROM ZTB_REQUEST
		UNION ALL
		SELECT SEQ, GB, '7', APP_FILE_NAME7, APP_ORIGINAL_NAME7, CREATE_DATE
		  FROM ZTB_REQUEST
		UNION ALL
		SELECT SEQ, GB, '8', APP_FILE_NAME8, APP_ORIGINAL_NAME8, CREATE_DATE
		  FROM ZTB_REQUEST  
		UNION ALL
		SELECT SEQ, GB, '9', APP_FILE_NAME9, APP_ORIGINAL_NAME9, CREATE_DATE
		  FROM ZTB_REQUEST  
  		) A
  WHERE APP_FILE_NAME <> ''
  ORDER BY GB, SEQ, NUM


