/**
 * 서류코드 Form (APFS_서류코드데이터.xlsx)
 * ntarget 	: 2023-05-19
 */
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01', 'NONE', '투자유치 후 지원사업', '', 0, '', '', 'N', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01A01', 'D01', '구매상담회 제출서류', '', 1, '', '', 'Y', 'N', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01B02', 'D01', '수출초보기업멘토링데이 제출서류', '', 1, '', '', 'Y', 'N', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01C03', 'D01', '팝업스토어 제출서류', '', 1, '', '', 'Y', 'N', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01D04', 'D01', '국내대규모박람회참가 제출서류', '', 1, '', '', 'Y', 'N', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01E05', 'D01', '해외박람회참가 제출서류', '', 1, '', '', 'Y', 'N', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01F06', 'D01', '수요자제안형마케팅 제출서류', '', 1, '', '', 'Y', 'N', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01G07', 'D01', '인플루언서마케팅 제출서류', '', 1, '', '', 'Y', 'N', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01H08', 'D01', 'PR·콘텐츠마케팅 제출서류', '', 1, '', '', 'Y', 'N', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01I09', 'D01', '온라인교육 제출서류', '', 1, '', '', 'Y', 'N', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01J10', 'D01', '온라인마케팅 제출서류', '', 1, '', '', 'Y', 'N', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01K11', 'D01', '스케일업프로그램 제출서류', '', 1, '', '', 'Y', 'N', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01L12', 'D01', '후속투자유치지원 제출서류', '', 1, '', '', 'Y', 'N', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01M12', 'D01', '농식품산업투자생태계활성화컨퍼런스 제출서류', '', 1, '', '', 'Y', 'N', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'NONE', '농식품크라우드펀딩지원사업', '', 0, '', '', 'N', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02A01', 'D02', '사업계획서/제품설명자료 등', '*첨부파일 내 개인정보 삭제 후 제출 요망', 1, '', '', 'N', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02A02', 'D02', '사업자등록증', '', 1, '', '', 'N', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02A03', 'D02', '법인등기부등본', '*법인사업자는 제출 필수', 1, '', '', 'N', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02A04', 'D02', '법인인감증명서', '*법인사업자는 제출 필수(주민번호 뒷자리 삭제)', 1, '', '', 'N', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02B01', 'D02', '사업자등록증', '', 1, '', '', 'N', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02B02', 'D02', '법인등기부등본', '*법인사업자는 제출 필수', 1, '', '', 'N', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02B03', 'D02', '법인인감증명서', '*법인사업자는 제출 필수(주민번호 뒷자리 삭제)', 1, '', '', 'N', 'N', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02B04', 'D02', '청구서스캔', '*수수료 지원 양식에 맞춰 작성', 1, '양식.hwp', '', 'Y', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02B05', 'D02', '거래내역서', '', 1, '', '', 'N', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02B06', 'D02', '지출증빙', '', 1, '', '', 'N', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02B07', 'D02', '컨설팅업체 사업자등록증', '', 1, '', '', 'N', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02B08', 'D02', '농식품경영체 통장사본', '', 1, '', '', 'N', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02C01', 'D02', '사업자등록증', '', 1, '', '', 'N', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02C02', 'D02', '법인등기부등본', '', 1, '', '', 'N', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02C03', 'D02', '법인인감증명서', '', 1, '', '', 'N', 'N', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02C04', 'D02', '청구서스캔', '*수수료 지원 양식에 맞춰 작성', 1, '양식.hwp', '', 'Y', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02C05', 'D02', '세금계산서/중계사발행', '', 1, '', '', 'N', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02C06', 'D02', '정산내역서/중계사발행', '', 1, '', '', 'N', 'Y', '100000', now() );
INSERT INTO TB_PAPE_CODE(DCMNT_CD, UP_DCMNT_CD, DCMNT_NM, DCMNT_CM_NM, LMT_CNT, FILE_NM, FILE_PATH, DWNLD_TRGT_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02C07', 'D02', '농식품경영체 통장사본', '', 1, '', '', 'N', 'Y', '100000', now() );

COMMIT;

/**
 * 신청서류맵핑 Form (APFS_서류코드데이터.xlsx)
 * 		- TASK_SE_CD 	: D01:투자유치후, D02:크라우드펀딩
 * 		- DTL_SE_CD 	: SA02:구매상담회.....SC03:수수료
 * 		- APLY_SE_CD	: 20:경영체회원, 40:개인회원
 * 
 * ntarget 	: 2023-05-19
 */
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01', 'SA001', '20', 'D01A01', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01', 'SA002', '20', 'D01B02', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01', 'SA003', '20', 'D01C03', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01', 'SA004', '20', 'D01D04', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01', 'SA005', '20', 'D01E05', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01', 'SA006', '20', 'D01F06', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01', 'SA007', '20', 'D01G07', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01', 'SA008', '20', 'D01H08', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01', 'SA019', '20', 'D01I09', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01', 'SA010', '20', 'D01J10', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01', 'SA011', '20', 'D01K11', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01', 'SA012', '20', 'D01L12', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D01', 'SA013', '20', 'D01M13', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC014', '20', 'D02A01', 'N', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC014', '20', 'D02A02', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC014', '20', 'D02A03', 'N', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC014', '20', 'D02A04', 'N', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC015', '20', 'D02B01', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC015', '20', 'D02B02', 'N', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC015', '20', 'D02B03', 'N', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC015', '20', 'D02B04', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC015', '20', 'D02B05', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC015', '20', 'D02B06', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC015', '20', 'D02B07', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC015', '20', 'D02B08', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC016', '20', 'D02C01', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC016', '20', 'D02C02', 'N', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC016', '20', 'D02C03', 'N', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC016', '20', 'D02C04', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC016', '20', 'D02C05', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC016', '20', 'D02C06', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC016', '20', 'D02C07', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC014', '40', 'D02A01', 'N', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC015', '40', 'D02B04', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC015', '40', 'D02B05', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC015', '40', 'D02B06', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC015', '40', 'D02B07', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC015', '40', 'D02B08', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC016', '40', 'D02C04', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC016', '40', 'D02C05', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC016', '40', 'D02C06', 'Y', 'Y', '100000', now());
INSERT INTO TB_PAPE_MNG (TASK_SE_CD, DTL_SE_CD, APLY_SE_CD, DCMNT_CD, ESNTL_YN, USE_YN, RGTR_NO, REG_YMD) VALUES ('D02', 'SC016', '40', 'D02C07', 'Y', 'Y', '100000', now());
COMMIT;
